#!/bin/bash
source ~/.bash_profile
echo $EMPIREDIR
open -a XQuartz.app
export PATH="/opt/X11/bin:$PATH"
if [ -z $EMPIREDIR ]; then
    echo "EMPIREDIR not set, using '..' for now"
    EMPIREDIR='..'
    export EMPIREDIR
fi

$EMPIREDIR/scripts/Xrun.mac &
exit
