#! /bin/sh -
#script to compile EMPIRE II package
cd source
make
make ecis
cd ../util/empend
make
cd ../x4toc4
make
cd ../c4sort
make
cd ../plotc4
make
cd ../fixup
make
cd ../sixtab
make
cd ../lsttab
make
cd ../legend
make
cd ../c4zvd
make -f c4dat.mak
make -f datzvd.mak
make -f endzvd.mak
cd ../../EXFOR
make
cd ../
exit
