#! /bin/sh -
#script to compile EMPIRE II package
cd source
make
make ecis
cd ../util/empend
make
cd ../x4toc4
make
cd ../c4sort
make
cd ../plotc4
make
cd ../fixup
make
cd ../sixtab
make
cd ../lsttab
make
cd ../legend
make
cd ../c4zvd
make -f c4dat.mak
make -f datzvdl.mak
make -f endzvd.mak
make -f curzvdl.mak
make -f pntdatl.mak
cd ../../EXFOR
make
cd ../
exit
