#! /bin/sh -
#script to format EMPIRE II output
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
work=`pwd`
if [ "$1" = "" ]
   then
echo 'Inputs ready to run'
echo ' '
ls *.endf
echo ' '
echo -n 'Choose one of the above (without .endf extention!): '
read file
fi


# RECONSTRUCT INELASTIC, (N,P) AND (N,A) REACTIONS WITH FIXUP

rm $file-full.endf 2>/dev/null
cat >FIXUP.INP <<EOF
12101011111001
$file.endf
$work/$file-tmp.endf
S  4=+( 50, 91)
S103=+(600,649)
S104=+(650,699)
S105=+(700,749)
S106=+(750,799)
S107=+(800,849)

 0.00000+00 0.00000+00          0          0${2}103

 0.00000+00 0.00000+00          0          0${2}107



EOF
$EMPIREDIR/util/fixup/fixup < FIXUP.INP
rm FIXUP.INP
mv FIXUP.LST $work/$file-log.fixup

# RUN STANEF

rm -f INPUT 2>/dev/null
cat >INPUT <<EOF
$file-tmp.endf
$file-full.endf
0

DONE
EOF
$EMPIREDIR/util/stanef/stanef <INPUT

#$work/$file.endf is the final ENDF output file

# remove left-over files
rm INPUT 2>/dev/null
rm angdis.cur 2>/dev/null
rm angdis.pnt 2>/dev/null
rm $file-tmp.endf 
exit
