#! /bin/sh -
#SCRIPT TO SORT C4 FILE 
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
work=`pwd`
if [ "$1" = "" ]
   then
    echo 'Inputs ready to run'
    echo ' '
    ls *c4
    echo ' '
    echo -n 'Choose one of the above (without .c4 extention!): '
    read file
fi
echo ' '
if [ -f $file-raw.c4 ]; then
   echo 'Original C4 file stored as :'  $file-raw.c4
else
   echo 'Backup of the original C4 file:'  $file-raw.c4
   cp $file.c4 $file-raw.c4
fi
echo ' '
ln  -sf $file.c4 C4.DAT
# SORT C4 FILE
ln -sf $EMPIREDIR/util/c4sort/iaea-std.dat iaea-std.dat
ln -sf $EMPIREDIR/util/c4sort/C4SORT.INP C4SORT.INP
ln -sf $EMPIREDIR/RIPL/levels/ RIPL_LEVELS

# RUN c4sort TO SORT C4 DATA   
# (pre-sorting is no longer necessary with updated ang_mu)
# $EMPIREDIR/util/c4sort/c4sort < C4SORT.INP

# ADD MU-BAR DATA TO THE C4 FILE
# (updated ang_mu reads the raw C4 file directly; input C4.SRT changed to C4.DAT)
cat >ANG_MU.INP<<EOF
C4.DAT
C4.TMP
EOF

# RUN ang_mu
$EMPIREDIR/util/ang_mu/ang_mu < ANG_MU.INP
echo ' '
mv C4.TMP C4.DAT

# RUN c4sort the second time TO SORT C4 DATA   
$EMPIREDIR/util/c4sort/c4sort < C4SORT.INP

mv C4.SRT $file.c4
echo ' '
if [ -s $file.c4 ]; then
  echo 'EXFOR sorted data in computational (c4) format are stored in : '$file.c4
else
  echo 'File with EXFOR data in computational (c4) format is EMPTY'
fi
echo ' '
rm ANG_MU.INP C4SORT.INP C4SORT.TMP C4.DAT iaea-std.dat c4sort.scr C4SORT.TM2
rm angdis.pnt angdis.p92 angdis.cur RIPL_LEVELS C4SORT.TM3 
exit
