#$Author: S Hoblit$
# build file for IO under Windows
# set C compiler
CC = gcc

# set fortran compiler:
FC     =  gfortran
FFLAGS = -O3 -fdefault-real-8

# define MODE = BLK if using block-mode I/O
# this is more efficient than fortran I/O
MODE = BLK

# set routines for line I/O
ifeq ($(MODE),BLK)
   LINIO = endf_blkwin.o
else 
   LINIO = endf_lr.o
endif

# make sure MAKE knows f90 extension
%.o : %.f90
	$(FC) $(FFLAGS) -c $<

OBJF = mf1.o mf2.o mf3.o mf4.o mf5.o mf6.o mf7.o mf8.o mf9.o\
       mf10.o mf12.o mf13.o mf14.o mf15.o mf23.o mf26.o mf27.o\
       mf28.o  mf31.o mf32.o mf33.o mf34.o mf35.o mf40.o

all : $(OBJF) c4_io.o endf.o
endf.o : $(OBJF) endf_base.o endf_cov.o endf_queue.o
endf_queue.o : $(OBJF)
endf_line.o : endf_win.o $(LINIO)
endf_base.o : endf_line.o
endf_cov.o : endf_base.o
$(OBJF) : endf_base.o endf_cov.o

clean:
	rm -f *.mod *.o
