C=======================================================================
C
C     GROUPIE COMMON
C
C=======================================================================
c-----01/07/07 - INCREASED TO 600,000 FROM 120,000.
      PARAMETER (MAXPOINT = 600000)
C
C     PAGED STORAGE FOR
C     1 = SPECTRUM
C     2 = TOTAL
C     3 = ELASTIC
C     4 = CAPTURE
C     5 = FISSION
C     6 = OTHER - NOT IN PAGING SYSTEM, ONLY IN MEMORY ARRAYS
C
      COMMON XPAGE(MAXPOINT,5),YPAGE(MAXPOINT,5)
C-----REPORT FOR EACH MAT
      PARAMETER (MAXMAT  = 1000)
      PARAMETER (MAXBAND = 5)
      COMMON/REPORT/ERBTAB(6,MAXMAT),ERLIB(25,MAXBAND),NBNTAB(MAXMAT),
     1 IZATAB(MAXMAT),LZA
C-----GROUP AVERAGED TOTAL STORAGE
      PARAMETER (MAXGROUP = 1000)
      COMMON/GROUPR/EGROUP(MAXGROUP+1),TOTAV(MAXGROUP+1),
     1 SPECTOUT(MAXGROUP+1),NGR,NGRP1,IGR
C-----PLOTTING COMMON = UNSHIELDED AND SHIELDED
      COMMON/PLOTCOM/XCPLOT(MAXGROUP,5,2)
C-----MULTI-BAND PARAMETER STORAGE
      COMMON/BANDID/WTBAND(6,MAXBAND,MAXMAT),XCBAND(6,MAXBAND,MAXMAT)
      COMMON/INTNRM/XCINT(25,6),XCNORM(25)
      COMMON/MATERR/ERMAT(25,MAXBAND),ERNOW(25,MAXBAND)
      COMMON/SIMPLE/XCFI(25,6),AVEXP(25),AVNORM(25),SIGMAB(25)
      COMMON/MISSIT/FST(25),DFST(25),DDFST(25),DEAVST(25)
      COMMON/ELPAS1/SHIELD(25),YLOW(5),YHIGH(5),YLOWP1(5),YLOWP2(5),
     1 YLOWP3(5),YHIGHP1(5),YHIGHP2(5),YHIGHP3(5)
      CHARACTER*4 POINT,REACT2,REACT3
      COMMON/ELPASC/POINT(25),REACT2(2,6),REACT3(2,6)
c-----MULTI-GROUP OUTPUT TO ENDF/B FORMAT
      PARAMETER (MAXOUT   =  3000)
      COMMON/GROUPOUT/XOUT(MAXOUT),YOUT(MAXOUT)
