TARGETS = sigma1 recent linear groupie dictin  fixup legend merger mixer sixpak spectra virgin activate convert relabel comhard evalhard

install: all
	cd SOURCES; make install FC=$(FC)

all: 
	cd SOURCES; make all FC=$(FC)

test:

clean:
	cd SOURCES; make clean
	rm -f $(TARGETS)
