#....Intel FORTRAN compiler
#FC     =  ifort 
#----GNU FORTRAN compiler (FEDORA 7)
FC     = gfortran
#----standard f90 FORTRAN compiler
#FC	= f90

OBJF =	stanef.o


stanef:   $(OBJF)
	$(FC) -o $@ $(OBJF)


