#! /bin/sh -
#script to  display exp. and calculated data with ZVView by V. Zerkin

XWIN=`uname`
if [ "$XWIN" = "Darwin" ] 
then
export DISPLAY=:0
fi
file=$1
MT=$2
work=`pwd`
if [ "$1" = "" ]
   then
echo 'Inputs ready to run'
echo ' '
ls *endf  
echo ' '
echo -n 'Choose one of the above (without .endf extention!): '
read file
fi                          
if [ "$2" = "" ]
   then
echo -n 'Input MT number to be plotted: '
read MT
fi                          

# FIRST RECONSTRUCT (N,N), (N,P), AND (N,A) REACTIONS WITH FIXUP

if [ ! -f $file-s.endf ]; then
   #  FIXUP input expects file named OUTPUT.ENDF:   
   ln -sf $work/$file.endf OUTPUT.ENDF
   ln -sf $EMPIREDIR/util/fixup/FIXUP.INP FIXUP.INP
    
   $EMPIREDIR/util/fixup/fixup
   rm OUTPUT.ENDF FIXUP.INP
   mv FIXUP.ENDF $work/$file-f.endf

   # RUN SIXTAB TO PREPARE FILE 6 FOR PLOTTING

   ln -sf $work/$file-f.endf ENDF.IN
   ln -sf $EMPIREDIR/util/sixtab/SIXTAB.INP SIXTAB.INP

   $EMPIREDIR/util/sixtab/sixtab
   rm ENDF.IN SIXTAB.INP
   mv ENDF.OUT $work/$file-s.endf
   if  [ -f $file-s.endf ]; then
      rm $file-f.endf 2>/dev/null
   fi   

fi

# RUN ZVD
c4zvd_dir=$EMPIREDIR/util/c4zvd
c4zvd33_dir=$EMPIREDIR/util/endf33zvd

ln -sf $work/$file-s.endf Present
ln -sf $work/$file.c4 c4
#$c4zvd_dir/c4zvv $MT $file 
rm tmp.dat c4.zvd end.zvd $file-$MT.zvd  zv*.ps zv*.eps 2>/dev/null
$c4zvd_dir/c4dat4l.exe c4 tmp.dat MF=3 MT=$MT
$c4zvd_dir/datzvdl.exe tmp.dat c4.zvd
$c4zvd_dir/endzvdl.exe A $MT Present end.zvd
$c4zvd33_dir/endf33zvd_l.exe -mt:$MT -c:$file-$MT-cov.zvd -u:$file-$MT-unc.zvd Present
echo #!zvview.exe >$file-$MT.zvd
cat c4.zvd >$file-$MT.zvd
cat end.zvd >>$file-$MT.zvd
$c4zvd_dir/zvview.exe -p:$file-$MT $file-$MT.zvd ps01.tit/c

if [ -f zv00.ps ]; then
   mv zv00.ps $work/$file-$MT.ps
fi
if [ -f zv00.eps ]; then
   mv zv00.eps $work/$file-$MT.eps
fi
rm c4.zvd end.zvd tmp.dat 2>/dev/null
exit
