#!/bin/bash
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi
MT=$1
file=$2 
echo ' '
echo 'Running ZVView plot for:'
echo 'MT='$1
echo $file'='$2 
rm tmp.dat c4.zvd end.zvd $file-$MT.zvd
$EMPIREDIR/util/c4zvd/c4dat4l.exe c4 tmp.dat MF=3 MT=$1
$EMPIREDIR/util/c4zvd/datzvdl.exe tmp.dat c4.zvd
$EMPIREDIR/util/c4zvd/endzvdl.exe A $MT Present end.zvd
echo #!zvview.exe >$file-$MT.zvd
cat c4.zvd >$file-$MT.zvd
cat end.zvd >>$file-$MT.zvd
rm c4.zvd end.zvd tmp.dat 2>/dev/null         
$EMPIREDIR/util/c4zvd/zvview.exe $file-$MT.zvd ps01.tit/c


