CC
CC    PRIVCOM19.FOR
CC
      VR0i   = VR0
      VR1i   = VR1
      VR2i   = VR2
      VR3i   = VR3
      VRLAi  = VRLA
      ALAVRi = ALAVR

      WD0i   = WD0
      WD1i   = WD1
      WDA1i  = WDA1
      WDBWi  = WDBW
      WDWIDi = WDWID
      ALAWDi = ALAWD

      WC0i   = WC0  
      WC1i   = WC1 
      WCA1i  = WCA1 
      WCBWi  = WCBW 
      WCWIDi = WCWID
      BNDCi  = BNDC 

      VSi    = VS   
      ALASOi = ALASO
      WS0i   = WS0  
      WS1i   = WS1  
      WSBWi  = WSBW 
      WSWIDi = WSWID

      RRi    = RR   
      RRBWCi = RRBWC
      RRWIDi = RRWID
      PDISi  = PDIS 
      AR0i   = AR0  
      AR1i   = AR1  

      RDi    = RD   
      AD0i   = AD0  
      AD1i   = AD1  
      RCi    = RC   
      AC0i   = AC0  
      AC1i   = AC1  

      RWi    = RW   
      AW0i   = AW0  
      AW1i   = AW1  
      RSi    = RS   
      AS0i   = AS0  
      AS1i   = AS1  

      RZi    = RZ   
      RZBWCi = RZBWC
      RZWIDi = RZWID
      AZi    = AZ   
      CCOULi = CCOUL
      ALFi   = ALF  

      CISOi  = CISO 
      WCISOi = WCISO
      WDISOi = WDISO
      EAi    = EA   
      WDSHIi = WDSHI
      WDWID2i= WDWID2
      
      ALFNEWi= ALFNEW
      VRDi   = VRD  
      CAVRi  = CAVR 
      CARRi  = CARR 
      CAARi  = CAAR 
      CARDi  = CARD 
      CAACi =  CAAC 
