      COMMON/OPT/XAD(25),GR(25),XAD1(25),XAD2(25),EP(25),EPSGR(25),NV
      COMMON/OPB/C,GRR(25),FM,EPS1,NRL
      COMMON/CHISQC/FU,NNTT

      COMMON/IREAD/VR0i,VR1i,VR2i,VR3i,VRLAi,ALAVRi,
     *               WD0i,WD1i,WDA1i,WDBWi,WDWIDi,ALAWDi,
     *               WC0i,WC1i,WCA1i,WCBWi,WCWIDi,BNDCi,
     *               VSi,ALASOi,WS0i,WS1i,WSBWi,WSWIDi,
     *               RRi,RRBWCi,RRWIDi,PDISi,AR0i,AR1i,
     *               RDi,AD0i,AD1i,RCi,AC0i,AC1i,
     *               RWi,AW0i,AW1i,RSi,AS0i,AS1i,
     *               RZi,RZBWCi,RZWIDi,AZi,CCOULi,ALFi,
     *               CISOi,WCISOi,WDISOi,EAi,WDSHIi,WDWID2i,
     *               ALFNEWi,VRDi,CAVRi,CARRi,CAARi,CARDi,
     *               CAACi 

