C     *******************************************************
C     START of privcom21  
C     *******************************************************
C==========================================================================
C     PRIVATE COMMONS FOR EACH PARALLEL THREAD TO BE USED AS INCLUDE BLOCK
C     Filename and EMPIRE flags

      LOGICAL EMPIRE, unformatted
      CHARACTER*20 fname 
      
      COMMON/INOUT/fname,EMPIRE,unformatted
     
     

C     *******************************************************
C     END of pricom21
C     *******************************************************
