CC
CC    PRIVCOM18.FOR
CC
      VR0   = VR0i
      VR1   = VR1i
      VR2   = VR2i
      VR3   = VR3i
      VRLA  = VRLAi
      ALAVR = ALAVRi

      WD0   = WD0i
      WD1   = WD1i
      WDA1  = WDA1i
      WDBW  = WDBWi
      WDWID = WDWIDi
      ALAWD = ALAWDi

      WC0   = WC0i  
      WC1   = WC1i  
      WCA1  = WCA1i 
      WCBW  = WCBWi 
      WCWID = WCWIDi
      BNDC  = BNDCi 

      VS    = VSi   
      ALASO = ALASOi
      WS0   = WS0i  
      WS1   = WS1i  
      WSBW  = WSBWi 
      WSWID = WSWIDi

C     RR    = RRi   
      RRBWC = RRBWCi
      RRWID = RRWIDi
      PDIS  = PDISi 
C     AR0   = AR0i  
C     AR1   = AR1i  

C     RD    = RDi   
      AD0   = AD0i  
      AD1   = AD1i  
C     RC    = RCi   
      AC0   = AC0i  
      AC1   = AC1i  

C     RW    = RWi   
      AW0   = AW0i  
      AW1   = AW1i  
C     RS    = RSi   
      AS0   = AS0i  
      AS1   = AS1i  

C     RZ    = RZi   
      RZBWC = RZBWCi
      RZWID = RZWIDi
      AZ    = AZi   
      CCOUL = CCOULi
      ALF   = ALFi  

      CISO  = CISOi 
      WCISO = WCISOi
      WDISO = WDISOi
      EA    = EAi   
      WDSHI = WDSHIi
      WDWID2= WDWID2i
      
      ALFNEW= ALFNEWi
      VRD   = VRDi  
      CAVR  = CAVRi 
      CARR  = CARRi 
      CAAR  = CAARi 
      CARD  = CARDi 
      CAAC =  CAACi 
