#!/usr/bin/env python
# encoding=utf-8
"""
watch qsub, report when queue is empty
"""

import os
import sys
import time

def monitorQueue(nProc):
    """
    watch 'qstat' every N seconds
    report when nProc or fewer jobs remain
    if nProc==0 report when queue is empty
    """
    from subprocess import Popen, PIPE
    # seconds to wait before checking again:
    N = 15
    # number of lines in qstat report (handle empty queue below)
    nProc = int(nProc)
    nLines = nProc+3
    
    while True:
        qstat = Popen('qstat',shell=True, bufsize=-1, stdout=PIPE,
                stderr=PIPE,close_fds=True)
        o,e = qstat.communicate()
        o = o.split("\n")
        if len(o)==1:
            sys.stdout.write("\n\nQueue is empty\n")
            return 0
        elif len(o)<=nLines:
            return nProc
        time.sleep(N)

if __name__ == '__main__':
    start = time.time()
    if len(sys.argv)==2:
        monitorQueue(sys.argv[1])
    else:
        monitorQueue(0)
    stop = time.time()
    sys.stdout.write("Elapsed time: %.2f seconds\n" % (stop-start))

