#!/bin/bash
#Script to produce ZVV plots comparing four sets of calculations
#with experimental data (all MTs for a single material)
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

suf=$1
root=$2
dir1=$3
name1=$4
dir2=$5
name2=$6
dir3=$7
name3=$8
dir4=$9
name4=$10

MTs=( 1  2  4 16 17 18 22 28 45 102 103 107 51 52 53 54 55 \
     56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 \
     74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 )

for i in MTs "${MTs[@]}"; do
$EMPIREDIR/scripts/mtacomp i  $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3 $dir4 $name4
done


exit
