#!/bin/bash
#Script to produce ZVV plots comparing three sets of calculations
#with experimental data (all MTs for a single material)

suf=$1
root=$2
dir1=$3
name1=$4
dir2=$5
name2=$6
dir3=$7
name3=$8

../scripts/mtacomp 1   $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
../scripts/mtacomp 2   $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
../scripts/mtacomp 4   $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
../scripts/mtacomp 16  $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
../scripts/mtacomp 17  $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
../scripts/mtacomp 18  $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
../scripts/mtacomp 22  $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
../scripts/mtacomp 28  $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
../scripts/mtacomp 45  $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
../scripts/mtacomp 102 $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
../scripts/mtacomp 103 $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
../scripts/mtacomp 107 $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
../scripts/mtacomp 112 $suf $root $dir1 $name1 $dir2 $name2 $dir3 $name3
exit
