#! /bin/sh -
#script to add resonance parameters to the ENDF-6 formatted file
# RUN ENDRES TO INCLUDE RESONANCE PARAMETRS (FILE 2)
file=$1
work=`pwd`

#If local file with resonance parameters exist then use it
if [ -f $file-res.endf ]; then
cat >ENDRES.INP <<EOF
empire.end
$file-res.endf
endf.dat
0

EOF
mv -f ENDRES.INP ../util/endres/
cp -f $file-res.endf ../util/endres/
fi

cd ../util/endres/
rm empire.end endf.dat 2>/dev/null
ln -sf $work/$file.endf empire.end
./endres <ENDRES.INP
rm empire.end 
rm $file-res.endf 
mv endf.dat $work/$file.endf
mv endres.lst $work/$file-log.endres
cd $work
#$work/$file.endf is the final ENDF output file

# RUN STANEF

rm -f INPUT
cat >INPUT <<EOF
$file.endf
$file-stan.endf
0

DONE
EOF
../util/stanef/stanef <INPUT
mv $file-stan.endf $file.endf

../scripts/process $file

# remove left-over files
rm INPUT 2>/dev/null

