#! /bin/sh -
# Script to move essential results of the calculations and all eps plots to another directory
# for later comparison with other calculations. All input files needed to
# reproduce calculations are preserved.
# Usage:
# memorize dir root
# where:
#    dir - name of the directory (subdirectory of the ./Archive directory)
#    root - root name of the project, e.g. Ta181 for the project with input file Ta181.inp 


echo "Number of arguments" $#
if [ $# = 2 ]; then
   file=$1
   dir="Archive/"$2
elif [ $# = 1 ]; then
   read -p "Enter name of the directory:"  dirName
   dir="Archive/"$dirName
else
   echo "Script to move results of most recent calculations including all input files "
   echo "necessary to repeat calculations as well as all eps plots to a specified directory. "
   echo "The script can be copied from the empire/scripts directory to the working directory "
   echo "and personalized e.g., to copy zvd files or to preserve them in the working directory."
   echo "Two arguments need to be provided."
   echo " "
   echo "Usage: memorize 'directory_name' 'root_name'"
   exit
fi

dir=$1
file=$2

if [ -d $dir ]; then
   echo 'O.K. directory:'  $dir ' exists'
   else
   mkdir $dir              
#   touch $dir/ho
   echo 'Have created directory:'  $dir
fi                          


# $dir could be added to the file names for indetification e.g. cp $file.lev $dir/$file-$dir.lev
cp $file-lev.col $dir 2>>/dev/null
cp $file-omp.ripl $dir 
# cp $file.endf Archive/$dir
cp $file.lev $dir
cp $file-omp.dir $dir  
cp $file-s.endf $dir   
cp $file.inp $dir      
cp $file-inp.fis $dir 2>>/dev/null      
cp $file.xsc $dir
mv *.eps $dir
# Have the next line uncommented to store also *Id*zvd  files
mv *Id*.zvd
echo 'Copied ' $file ' input files and ' $file '-s.endf file while all plot files were moved to Archive/' $dir

exit

