#! /bin/sh -
#SCRIPT TO RUN X4TOC4       
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

work=`pwd`
file=$1
rm X4.DAT NEWX4.DAT X4TOC4.LST C4.DAT 2>/dev/null
# Pointing to the nex EXFOR dictionary located in the $EMPIREDIR/EXFOR 
# directory which is automatically updated by the parseC4 python script  
ln -sf $EMPIREDIR/util/x4toc4/EXFOR14A.DAT EXFOR14A.DAT
#ln -sf $EMPIREDIR/EXFOR/EXFOR14A.DAT EXFOR14A.DAT
ln -sf $EMPIREDIR/util/x4toc4/EXFOR24A.DAT EXFOR24A.DAT
ln -sf $EMPIREDIR/util/x4toc4/EXFOR25A.DAT EXFOR25A.DAT
ln  -sf $work/$file.exf X4.DAT

$EMPIREDIR/util/x4toc4/x4toc4
rm X4.DAT
rm EXFOR14A.DAT EXFOR24A.DAT EXFOR25A.DAT

mv NEWX4.DAT $file.x42c4_errs
mv X4TOC4.LST $file.x42c4_lst
mv C4.DAT $file.c4
if [ ! -s $file.c4 ]; then
   echo 'File with EXFOR data in computational C4 format is EMPTY'
   exit
fi
if [ -s $file.c4 ]; then
   echo 'EXFOR data converted to computational format and stored in '$file-unsorted.c4
   echo 'WARNING: Existing file ' $file.c4 ' was not overwritten!'
   echo 'Hit ENTER to continue...'
   read aaa
else
   echo 'EXFOR data converted to computational format and stored in '$file.c4
fi
exit

