#! /bin/sh -
#SCRIPT TO UN X4TOC4       

work=`pwd`
file=$1
cd ../util/x4toc4
rm X4.DAT NEWX4.DAT X4TOC4.LST C4.DAT 2>/dev/null
ln  -sf $work/$file.exf X4.DAT
./x4toc4
rm X4.DAT
cd $work
mv ../util/x4toc4/NEWX4.DAT $file.x42c4_errs
mv ../util/x4toc4/X4TOC4.LST $file.x42c4_lst
mv ../util/x4toc4/C4.DAT $file.c4
if [ -s $file.c4 ]; then
   echo 'EXFOR data in computational format are stored in: '$file.c4
   else
   echo 'File with EXFOR data in computational format is EMPTY'
fi
exit








