#!/bin/bash
#Script to run c4service code multiple times on the existing *.c4 file  
#to perform following operations:
# - removing experiments
# - smoothing experiments (preserves integral)
# - croping energy range of the experiments
# - modifying experimental values and their uncertainties
#Detailed instructions will be give during execution
#Usage:
# c4serv root-file-name editor
# 'editor' is a name of editor to open *-c4.inp file for making changes
# if not specified defaults are gvim for Linux and MacVim for Mac

if [ -z $EMPIREDIR ]; then
    echo " Please set the 'EMPIREDIR' environment variable."
    echo " See Empire v3 documentation for more information."
    exit
fi
work=`pwd`
file=$1
if [ "$1" = "" -o "$1" = "-h" -o "$1" = "--help" -o "$1" = "-help" ]
then
   echo " Usage:"
   echo " c4serv file_root_name editor_name"
   echo " "
   echo "    file_root_name - name of the *.c4 file without .c4 extension "
   echo "    editor_name    - single-word name of the preferred editor"
   echo " "
   echo " EMPIRE naming convention is assumed thus C4 file must have .c4 extension."
   echo " The editor_name parameter is optional and if missing the default is gvim."
   echo " c4serv facilitates operattiion of the c4service code by openinng its input"
   echo " and cycling through editing the input and running the code. In each cycle "
   echo " a neutral input is regenerated. To stop a cycle unswer 'no' to the request"
   echo " wether to run the c4service code."
   exit
else
   file=$1
fi
edit=$2
# Set editor for Linux or Mac (vim is a default for both)
XWIN=`uname`
if [ "$XWIN" = "Darwin" ] 
then
   if [ "$edit" = "" ] 
   then 
      edit="open -a MacVim"
   else
      edit="open -a "$edit
   fi
   echo " Editor open command on Mac set to "$edit
   echo " To use another editor specify it as the second argument when calling this script"
else
   if [ "$edit" = "" ] 
   then 
      edit="gvim"
   fi
   echo " Editor command set to "$edit
   echo " To use another one specify it as the second argument when calling this script"
fi

# Backup the original C4 file
if [ ! -s $file-orig.c4 ]; then
   cp $file.c4 $file-orig.c4
   echo " Your C4 file has been copied to "$file"-orig.c4"
fi   

yesno="y"
while [ "$yesno" == "y" ]; do
   rm $file-c4.inp 2>/dev/null
   $EMPIREDIR/util/c4service/c4service $file
   $edit $file-c4.inp 
   echo " Edit and SAVE input file *-c4.inp then return here to rerun c4service"
   # echo " You may use Zvv plots from GUI to check your changes"
   echo " Do you want to run c4service (y/n)"
   read yesno
   if [ "$yesno" == "y" ]; then
      echo " "
      echo " "
   else
      echo " Showing "$file"-c4.log with list of changes"
      $edit $file-c4.log
      exit
   fi     

done