#! /bin/sh -
# Script to clean the test-cases directory, keeping only original files
#
cd $EMPIREDIR/test-cases
mkdir TeMpOrArYdIr
mv *-ref.* TeMpOrArYdIr/
$EMPIREDIR/scripts/clean a-ni58-pcross  
$EMPIREDIR/scripts/clean HI-pcross-ccfus
$EMPIREDIR/scripts/clean pd105          
$EMPIREDIR/scripts/clean pu240          
$EMPIREDIR/scripts/clean u238-photo-fiss          
rm *.zvd file* spec ecis* >& /dev/null
mv TeMpOrArYdIr/* ./
rm -r TeMpOrArYdIr
