#! /bin/sh -
# Script to clean the benchmarks directory, keeping only original files
#
cd $EMPIREDIR/benchmarks
mkdir TeMpOrArYdIr
mv *-ref.* TeMpOrArYdIr/
mv th232-rot-vib-lev.col TeMpOrArYdIr/
mv u238-HFB-num-fis-tun-inp.fis TeMpOrArYdIr/
cp u238-HFB-num-fis-tun.inp TeMpOrArYdIr/ 
$EMPIREDIR/scripts/clean a-ni58-pcross 
$EMPIREDIR/scripts/clean d-au197 
$EMPIREDIR/scripts/clean fe54-blind 
$EMPIREDIR/scripts/clean fe54-vib-CC-direct-2 
$EMPIREDIR/scripts/clean HI-pcross-ccfus 
$EMPIREDIR/scripts/clean n_eu153-dir-msc-msd 
$EMPIREDIR/scripts/clean ni62-th-EGSM 
$EMPIREDIR/scripts/clean n-na23-prim-gam  
$EMPIREDIR/scripts/clean n-zr92-soft--dccomp 
$EMPIREDIR/scripts/clean p-th232
$EMPIREDIR/scripts/clean p-tl205
$EMPIREDIR/scripts/clean test-HRTW-fis
$EMPIREDIR/scripts/clean test-LD-mo100 
$EMPIREDIR/scripts/clean test-PE-models 
$EMPIREDIR/scripts/clean th232-rot-vib 
$EMPIREDIR/scripts/clean u235-blind 
$EMPIREDIR/scripts/clean u235-pfns-nubar  
$EMPIREDIR/scripts/clean u238-blind 
$EMPIREDIR/scripts/clean u238-gf               
$EMPIREDIR/scripts/clean u238-HFB-num-fis 
$EMPIREDIR/scripts/clean u238-HFB-num-fis-tun 
$EMPIREDIR/scripts/clean u238-HFB-par-fis 
$EMPIREDIR/scripts/clean u238-rot-CC-direct-2 
rm *.zvd file* spec ecis* >& /dev/null
mv TeMpOrArYdIr/* ./
rm -r TeMpOrArYdIr
