#!/bin/bash
for file in $*
do
dos2unix ${file}
#sed s/'HMS        0.'/'HMS        1.'/ ${file} >tmp
#mv tmp ${file}
#gv -landscape ${file}
#       /home/herman/empire/util/c4zvd/zvv95l.exe $file
done
