#! /bin/sh -
#script to format EMPIRE II output
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
MATid=$2
work=`pwd`
if [ "$2" = "" ]; then
  MATid='1111'
fi
if [ "$1" = "" ]
   then
echo 'Inputs ready to run'
echo ' '
ls *out
echo ' '
echo -n 'Choose one of the above (without .out extention!): '
read file
fi

# Checking if EMPIRE run sucessfully (at least .out was produced)
if [ ! -f $file.out ]; then
echo ' '
echo ' '
echo 'ERROR: EMPIRE output file '$file'.out is missing'
echo '     execute EMPIRE before formatting  !            '
echo ' '
echo ' Press any key to exit or <CTRL>-C to abort ...'
read yes
exit 1
fi

# Deleting previous file if exist
if [ -s $file-e.endf ]; then
  rm $file-e.endf 2>/dev/null
fi

#run EMPEND to format EMPIRE output into ENDF
# EMPEND takes .out file, writes endf. Also needs mesh, thinning, and MAT:
cat >EMPEND.INP <<EOF
$file.out                                                                                               
$file-e.endf                                                                   
1 
-1.0
$2
-1
LABLABLABL EVAL-`date "+%b%y"` AUTHORAUTHORAUTHORAUTHORAUTHORAUT
EOF
$EMPIREDIR/util/empend/empend <EMPEND.INP
rc=$?
mv empend.log $file-log.empend
rm EMPEND.INP empmf1.tmp
if [ $rc != 0 ] 
then
   echo ' '
   echo ' EMPEND crashed, check log file '$file'-log.empend for diagnostics!'
   echo ' Please notify Dr.A.Trkov at a.trkov@iaea.org                      '
   echo ' '
   echo ' Press any key to exit or <CTRL>-C to abort ...'
   read yes
   exit 3
fi

# RUN ENDRES (IF RESONANCE FILE IS PRESENT)
if [ -s $file-res.endf ]; then
   ln -sf $EMPIREDIR/util/endres/ENDRES.INP ENDRES.INP
   rm $file.endf 2>/dev/null
   ln -sf $file-e.endf empire.end
   ln -sf $file-res.endf ENDRES.DAT
   $EMPIREDIR/util/endres/endres < ENDRES.INP
   mv endf.dat $file-endres.endf
   mv endres.lst $file-log.endres
   rm ENDRES.INP empire.end ENDRES.DAT 2>/dev/null
else
   cp $file-e.endf $file-endres.endf
fi

# Deleting previous file if exist
if [ -s $file.endf ]; then
  rm $file.endf 2>/dev/null
fi

# RUN STANEF
rm -f INPUT 2>/dev/null
cat >INPUT <<EOF
$file-endres.endf
$file.endf
0

DONE
EOF
$EMPIREDIR/util/stanef/stanef <INPUT
rc=$?
if [ $rc != 0 ] 
then
   echo ' '
   echo ' STANEF crashed, please notify Dr.A.Trkov at a.trkov@iaea.org '
   echo ' '
   echo ' Press any key to exit or <CTRL>-C to abort ...'
   read yes
   exit $rc
fi

#echo $file.endf was produced by STANEF
# remove left-over files
rm INPUT 2>/dev/null
rm angdis.cur 2>/dev/null
rm angdis.pnt 2>/dev/null

# RECONSTRUCT INELASTIC, (N,P) AND (N,A) REACTIONS WITH FIXUP
# moved to a new script "rec-ch-part" called from a GUI(Execute)
$EMPIREDIR/scripts/rec-ch-part $file $MATid

exit
