#! /bin/sh -
#script to produce groupwise ENDF-6 file from a pointwise ENDF-6 file  

if [ "$1" = "-h" ]
   then
echo 'This script runs GROUPIE code on the ENDF formatted file, with extension .endf or -s.endf to produce groupwise cross sections.'
echo 'Group structure may be selected in the GROUPIE.INP file acccessible from the GUI under Options menue.'
echo 'Script argumet should be a name of the ENDF file WITHOUTOUT extension .endf or -s.endf'
echo 'If a file with -s.endf ending is available it will be used instead of .endf eliminating runs of RECENT and LINEAR. '
exit
fi


if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
work=`pwd`
if [ "$1" = "" ]
   then
echo 'Files ready to run'
echo ' '
ls *.endf
echo ' '
echo -n 'Choose one of the above (without -*.endf or .endf extention!): '
read file
fi  
                        
# Checking if the file processed by RECENT and LINEAR is available
if [ ! -f $file-s.endf ]; then
	echo ' '
	echo 'Input file '$file'-s.endf is missing               '
	echo 'RECENT and LINEAR will be run'
	echo ' '
	
	# Checking if input file available
	if [ ! -f $file.endf ]; then
	echo ' '
	echo 'ERROR: Input file '$file'.endf does not exist!!!            '
	echo 'Please note that script expects the ENDF file with extension .endf, but... '
	echo 'this extension must NOT be included in the script argument.'
	echo 'Press any key to exit and retry.'
	read yes
	exit 1
	fi
	
	# RUN LINEAR (In:ENDFB.OUT Out:LINEAR.OUT)
	
	rm LINEAR.INP 2>/dev/null
	ln -sf $EMPIREDIR/util/prepro/LINEAR.INP LINEAR.INP
	ln -sf $file.endf ENDFB.OUT
	$EMPIREDIR/util/prepro/linear <LINEAR.INP
	mv LINEAR.LST $work/$file-log.linear
	rm ENDFB.OUT LINEAR.INP 2>/dev/null
	
	
	# RUN RECENT (In:LINEAR.OUT  Out:RECENT.OUT)
	
	rm RECENT.INP 2>/dev/null
	ln -sf $EMPIREDIR/util/prepro/RECENT.INP RECENT.INP
	$EMPIREDIR/util/recent/recent <RECENT.INP
	mv RECENT.OUT  $work/$file-rec.endf
	mv RECENT.LST $work/$file-log.recent
#	rm ENDFB.IN 2>/dev/null
	rm LINEAR.OUT 2>/dev/null
	
	# SET -rec.endf FILE AS INPUT FOR GROUPIE 
	ln -sf $work/$file-rec.endf PREPRO17.OUT
else
	# SET -s.endf FILE AS INPUT FOR GROUPIE 
	ln -sf $work/$file-s.endf PREPRO17.OUT
fi

# RUN GROUPIE (In:PREPRO17.OUT Out:GROUPIE.OUT) 

ln -sf $EMPIREDIR/util/prepro/GROUPIE.INP GROUPIE.INP
$EMPIREDIR/util/Groupie/groupie <GROUPIE.INP
mv GROUPIE.OUT  $work/$file-grp.endf
mv GROUPIE.LST $work/$file-log.groupie



# REMOVE INTERMEDIATE FILES

rm ENDFB.IN, PREPRO17.OUT 2>/dev/null
rm $work/$file-rec.endf 2>/dev/null

exit
