#! /bin/sh -
#script to produce groupwise ENDF-6 file from a pointwise ENDF-6 file  
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
work=`pwd`
if [ "$1" = "" ]
   then
echo 'Files ready to run'
echo ' '
ls *-s.endf
echo ' '
echo -n 'Choose one of the above (without -s.endf extention!): '
read file
fi  
                        
# Checking if the file processed by RECENT and LINEAR is available
if [ ! -f $file-s.endf ]; then
echo ' '
echo 'Input file '$file'-s.endf is missing               '
echo 'RECENT and LINEAR will be run'
echo ' '

# Checking if input file available
if [ ! -f $file.endf ]; then
echo ' '
echo 'ERROR: Input file '$file'.endf does not exist!!!            '
echo ' '
echo ' Press any key to exit or <CTRL>-C to abort ...'
read yes
exit 1
fi

# RUN LINEAR

rm LINEAR.INP 2>/dev/null
ln -sf $file.endf ENDFB.IN
$EMPIREDIR/util/linear/linear
mv ENDFB.OUT  $work/$file-lin.endf
mv LINEAR.LST $work/$file-log.linear
rm ENDFB.IN 2>/dev/null

# RUN RECENT

rm RECENT.INP 2>/dev/null
ln -sf $work/$file-lin.endf ENDFB.IN
$EMPIREDIR/util/recent/recent
mv ENDFB.OUT  $work/$file-rec.endf
mv RECENT.LST $work/$file-log.recent
rm ENDFB.IN 2>/dev/null

# SET -rec.endf FILE AS INPUT FOR GROUPIE 
ln -sf $work/$file-rec.endf ENDFB.IN

fi

# SET -s.endf FILE AS INPUT FOR GROUPIE 
ln -sf $work/$file-s.endf ENDFB.IN

# RUN GROUPIE 

$EMPIREDIR/util/Groupie/groupie
mv ENDFB.OUT  $work/$file-grp.endf
mv GROUPIE.LST $work/$file-log.groupie



# REMOVE INTERMEDIATE FILES

rm ENDFB.IN, PLOTTAB.CUR 2>/dev/null
rm $work/$file-lin.endf 2>/dev/null
rm $work/$file-rec.endf 2>/dev/null

exit
