#! /bin/sh -
#SCRIPT TO RUN KALMAN (COVARIANCE MATRIX DETERMINATION)
file=$1
MAT=$3
MT=$2
work=`pwd`
if [ "$MAT" = "" ]
   then
   MAT=1111
findex.htmli
if [ "$MT" = "" ]
   then
   MT=102
fi

# Input for c4tokal and kalend
cat >KALEND.INP <<EOF
$MT $MAT 0
EOF
cp $file-inp.sen SENSITIVITY.INP

../util/kalman/genkal.pl $file

ln -s $file.c4 fort.1

../util/kalman/c4tokal<KALEND.INP >KALMAN.INP
rm fort.1
# correlations among experimental data
if [ ! -s $file-expcorr.kal ]; then
   cp fort.12 $file-expcorr.kal  
else
   cp $file-expcorr.kal fort.12     
fi
# correlations among model parameters
if [ ! -s $file-parcorr.kal ]; then
   cp fort.52 $file-parcorr.kal  
else
   cp $file-parcorr.kal fort.52     
fi
# experimental data
if [ ! -s $file-expxsc.kal ]; then
   cp fort.10 $file-expxsc.kal  
else
   cp $file-expxsc.kal fort.10     
fi

echo 'Edit Kalman input'
gvim KALMAN.INP
read dum
../util/kalman/kalman3 <KALMAN.INP >$file-out.kal
mv fort.13 $file-xsc.kal
mv fort.14 $file-cov.kal

# run KALEND

ln -s $file.endf ENDF.DAT
../util/kalman/form.pl $MAT $MT >$file-33-$MT.cov
../util/kalman/mf33.pl $MT <$file-33-$MT.cov
../util/kalman/mf33.pl -$MT <$file-33-$MT.cov >corrplot.dat
mv fort.18 $file-err-$MT.kal
gnuplot ../util/kalman/corr.plt

rm SENSITIVITY.INP
rm KALEND.INP
rm KALMAN.INP
rm ENDF.DAT
exit
