#! /bin/sh -
# Script to move essential results of the calculations and all eps plots to another directory
# for later comparison with other calculations. All input files needed to
# reproduce calculations are preserved.
# Usage:
# memorize dir root
# where:
#    dir - name of the directory (typical subdirectory of the working directory)
#    root - root name of the project, e.g. Ta181 for the project with input file Ta181.inp 

if [ $1 == '-h' ]; then
   echo 'Usage: directory root-name'
   exit
fi

dir=$1
file=$2

if [ -d $dir ]; then
   echo 'O.K. directory:'  $dir ' exists'
   else
   mkdir $dir              
#   touch $dir/ho
   echo 'Have created directory:'  $dir
fi                          


# $dir could be added to the file names for indetification e.g. cp $file.lev $dir/$file-$dir.lev
cp $file-lev.col $dir 2>>/dev/null
cp $file-omp.ripl $dir 
# cp $file.endf $dir
cp $file.lev $dir
cp $file-omp.dir $dir  
cp $file-s.endf $dir   
cp $file.inp $dir      
cp $file-inp.fis $dir 2>>/dev/null      
cp $file.xsc $dir
mv *.eps $dir
# uncomment the next line to store also *Id*zvd  files
# mv *Id*.zvd
# comment the next line to preserve *Id*zvd files in the working directory
rm *Id*.zvd
echo 'Copied ' $file ' input files and ' $file '-s.endf file while all *.eps files were moved to ' $dir

exit

