#!/bin/bash
#Script to produce ZVV plots comparing four sets of calculations
#with experimental data
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

export DISPLAY=:0

MT=$1
suf=$2
root=$3
dir1=$4
name1=$5
dir2=$6
name2=$7
dir3=$8
name3=$9
dir4=${10}
name4=${11}


if [ $suf == "-" ]; then
        suf=""
fi

rm $root-$MT$suf.zvd  2>/dev/null
ln -sf $EMPIREDIR/util/c4zvd/mt_x4r.txt mt_x4r.txt

#     FIRST ENDF SET AND EXFOR (.c4)
if [ "$name1" != "" ]; then
   rm EXFOR tmp.dat c4.zvd end1.zvd  $name1  2>/dev/null
   ln -sf $dir1/$root.c4 EXFOR
   ln -sf $dir1/$root-s.endf $name1
   $EMPIREDIR/util/c4zvd/c4dat4l.exe  EXFOR tmp.dat MF=3 MT=$MT 
   $EMPIREDIR/util/c4zvd/datzvdl.exe tmp.dat c4.zvd
   echo '#begin aa.tit' >>c4.zvd
#  put here counting of lines in c4.zvd and skip the rest if no real data inside  
   echo '[func]' >>c4.zvd
   echo 'color: 3' >>c4.zvd
   echo 'set: apply' >>c4.zvd
   echo '#end aa.tit' >>c4.zvd
   cat   c4.zvd >>$root-$MT$suf.zvd

   $EMPIREDIR/util/c4zvd/endzvdl.exe A $MT $name1 end1.zvd
   if [ -s end1.zvd ]; then
      echo '#begin aa.tit' >>end1.zvd
      echo '[func]' >>end1.zvd
      echo 'color: 2' >>end1.zvd
      echo 'thick: 2' >>end1.zvd
      echo 'set: apply' >>end1.zvd
      echo '#end aa.tit' >>end1.zvd
      cat end1.zvd >>$root-$MT$suf.zvd
   fi
   rm EXFOR $name1 2>/dev/null
fi
#     SECOND ENDF SET
if [ "$name2" != "" ]; then
   rm $name2 end2.zvd  2>/dev/null
   ln -sf $dir2 $name2
   $EMPIREDIR/util/c4zvd/endzvdl.exe A $MT $name2 end2.zvd
   if [ -s end2.zvd ]; then
      echo '#begin aa.tit' >>end2.zvd
      echo '[func]' >>end2.zvd
      echo 'color: 4' >>end2.zvd
      echo 'thick: 2' >>end2.zvd
      echo 'set: apply' >>end2.zvd
      echo '#end aa.tit' >>end2.zvd
      cat end2.zvd >>$root-$MT$suf.zvd
   fi
   rm $name2 2>/dev/null
fi

#     THIRD ENDF SET
if [ "$name3" != "" ]; then
   rm $name3 end3.zvd  2>/dev/null
   ln -sf $dir3 $name3
   $EMPIREDIR/util/c4zvd/endzvdl.exe A $MT $name3 end3.zvd
   if [ -s end3.zvd ]; then
      echo '#begin aa.tit' >>end3.zvd
      echo '[func]' >>end3.zvd
      echo 'color:  1' >>end3.zvd
      echo 'thick: 2' >>end3.zvd
      echo 'set: apply' >>end3.zvd
      echo '#end aa.tit' >>end3.zvd
      cat end3.zvd >>$root-$MT$suf.zvd
   fi
   rm $name3 2>/dev/null
fi

#     FOURTH ENDF SET
if [ "$name4" != "" ]; then
   rm $name4 end4.zvd  2>/dev/null
   ln -sf $dir4 $name4
   $EMPIREDIR/util/c4zvd/endzvdl.exe A $MT $name4 end4.zvd
   if [ -s end4.zvd ]; then
      echo '#begin aa.tit' >>end4.zvd
      echo '[func]' >>end4.zvd
      echo 'color:  5' >>end4.zvd
      echo 'thick: 2' >>end4.zvd
      echo 'set: apply' >>end4.zvd
      echo '#end aa.tit' >>end4.zvd
      cat end4.zvd >>$root-$MT$suf.zvd
   fi
   rm $name4 2>/dev/null
fi

#Run ZVV (uncomment the line below to see plots as they are produced)
#../util/c4zvd/zvview.exe $root-$MT$suf.zvd &
#rm tmp.dat c4.zvd 2>/dev/null
#rm end1.zvd end2.zvd end3.zvd 2>/dev/null
#rm mt_x4r.txt

exit
