#! /bin/sh -
# Script to run selected script: runE, format, verify, process, addresonances
# Created by V.Zerkin, IAEA-NDS, 2014-09-06
# Usage: $ multiE file_name MAT_number "actions"
#
echo par1=$0
echo par2=$1
echo par3=$2
echo par3=$3
#echo EMPIREDIR=$EMPIREDIR
#echo PWD=$PWD

file=$1
MAT=$2
actions=$3
dd=$EMPIREDIR/scripts

read -p " Press <Enter> key to continue ..."
 
    ls0=${#actions}
    i=0
    while [ $i -lt $ls0 ] ; do
	ch=${actions:i:1}
	#echo i=$i ch=[$ch]
	if [ "$ch" = "1" ] ; then
	    if [ "$i" = "0" ] ; then 
              python $dd/runE $file $MAT; 
              rc=$?
              if [[ $rc == 1 ]] ; then
                echo ' '
                echo ' EMPIRE input file '$file'.inp not found !'
                echo ' '
                read -p " Press <Enter> key to exit ..."
                echo ' '
                exit 1
              fi
              if [[ $rc == 2 ]] ; then
                echo ' '
                echo ' Check the long output '$file'.lst for diagnostics !'
                echo ' '
                read -p " Press <Enter> key to exit ..."
                echo ' '
                exit 1
              fi
              if [[ $rc != 0 ]] ; then
                echo ' '
                echo ' Indetermined error. Check the long output '$file'.lst for diagnostics !'
                echo ' '
                read -p " Press <Enter> key to exit ..."
                echo ' '
                exit 1
              fi
          fi
	    if [ "$i" = "2" ] ; then 
             $dd/format $file $MAT ; 
             rc=$?
             if [[ $rc != 0 ]] ; then
               exit 1
             fi
          fi
	    if [ "$i" = "4" ] ; then 
             $dd/verify $file $MAT ; 
             rc=$?
             if [[ $rc != 0 ]] ; then
               exit 1
             fi
          fi
	    if [ "$i" = "6" ] ; then 
             $dd/process $file $MAT ; 
             rc=$?
             if [[ $rc != 0 ]] ; then
               exit 1
             fi
          fi
	    if [ "$i" = "8" ] ; then 
             $dd/addresonances $file $MAT ;
             rc=$?
             if [[ $rc != 0 ]] ; then
               exit 1
             fi
          fi
	fi
	i=$(($i+1))
    done

exit
