#! /bin/sh -
file=$1
work=`pwd`
if [ "$1" = "" ]
   then
echo 'Data ready for plotting:'
echo ' '
ls *.c4
echo ' '
echo -n 'Choose one of the above (without .c4 extention!): '
read file
fi                          

if [ ! -f $file.c4 ]; then
   echo ' '
   echo ' '
   echo 'Error in pltlst; can not find: '$file.c4 
#  read bye
   exit
fi    

# RUN PLTLST TO PRODUCE LIST OF DATA 

cd ../util/pltlst
ln -sf $work/$file.c4 C4.DAT  
echo ' '
echo 'R U N N I N G    P L T L S T'
./pltlst
rm C4.DAT 
mv PLOTC4.LST $work/$file-log.plotc4
cd $work
exit
