#! /bin/sh -
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
work=`pwd`
if [ "$1" = "" ]
   then
echo 'Data ready for plotting:'
echo ' '
ls *-s.endf
echo ' '
echo -n 'Choose one of the above (without -s.endf extention!): '
read file
fi                          

if [ ! -f $file-s.endf ]; then
   echo ' '
   echo ' '
   echo 'Error in plot; can not find: '$file-s.endf 
#  read bye
   exit
fi    

# RUN PLOTC4 TO PRODUCE PLOTS

ln -sf $EMPIREDIR/util/plotc4/PLOTC4.INP PLOTC4.INP
ln -sf $EMPIREDIR/util/plotc4/ENDFMF.DAT ENDFMF.DAT
ln -sf $EMPIREDIR/util/plotc4/ENDFMT.DAT ENDFMT.DAT
ln -sf $EMPIREDIR/util/plotc4/ENDFZA.DAT ENDFZA.DAT
ln -sf $EMPIREDIR/util/plotc4/PLOT.CHR PLOT.CHR

ln -sf $work/$file.c4 C4.DAT
ln -sf $work/$file-s.endf ENDF.DAT
echo ' '
echo 'R U N N I N G    P L O T C 4'
$EMPIREDIR/util/plotc4/plotc4
rm PLOTC4.INP ENDFMF.DAT ENDFMT.DAT ENDFZA.DAT PLOT.CHR
rm C4.DAT ENDF.DAT
mv plot.ps $work/$file.ps
mv PLOTC4.LST $work/$file-log.plotc4
if [ "$2" = "" ]; then        
   ghostview -landscape $file.ps  
fi
exit
