#! /bin/sh -
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
work=`pwd`
if [ "$1" = "" ]
   then
echo 'Data ready for plotting:'
echo ' '
ls *-s.endf
echo ' '
echo -n 'Choose one of the above (without -s.endf extention!): '
read file
fi                          

if [ ! -f $file-s.endf ]; then
   echo ' '
   echo ' '
   echo 'Error in pltlst; can not find: '$file-s.endf 
   exit
fi    

if [ ! -f $file.c4 ]; then
   touch $file.c4
   echo ' '
   echo 'Plotlen created empty file: '$file.c4
fi    


# RUN PLTLEN TO PRODUCE LIST OF DATA 

ln -sf $work/$file-s.endf ENDF.DAT  
echo ' '
echo 'R U N N I N G    P L T L E N'

ln -sf $EMPIREDIR/util/pltlen/PLTLEN.INP PLTLEN.INP
$EMPIREDIR/util/pltlen/pltlen

rm ENDF.DAT  PLTLEN.INP
mv PLOTC4.LST $work/$file-log.plotc4 2>|/dev/null #ignore if same
exit
