#!/bin/bash
dir1=`pwd`
MTlist='1 2 4 16 102'
for filef in $*; do
  for MT in $MTlist; do
    ../scripts/mtacomp $MT def  `expr substr $filef 1 7` $dir1 `expr substr $filef 1 7`
    rm c4.zvd end1.zvd 
  done
done
