#! /bin/sh -
#script to process ENDF file (originating from EMPIRE) 
#through PREPRO in preparation for plotting
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
work=`pwd`
if [ "$1" = "" ]
   then
echo 'Files ready to run'
echo ' '
ls *endf
echo ' '
echo -n 'Choose one of the above (without .endf extention!): '
read file
fi                          


# RECONSTRUCT PROTON & ALPHA SPECTRA WITH FIXUP

rm $file-f2.endf 2>/dev/null
ln -sf $file.endf OUTPUT.ENDF
cat >FIXUP.INP <<EOF
12101011111001                                                              
OUTPUT.ENDF                                                                        
FIXUP.ENDF  
S203=+( 28, 28)+( 41, 41)+(103,103)
S207=+( 22, 25)+(107,109)+(112,114)

 0.00000+00 0.00000+00          0          0${2}203

 0.00000+00 0.00000+00          0          0${2}207







                                                                 
EOF

$EMPIREDIR/util/fixup/fixup < FIXUP.INP
rm OUTPUT.ENDF
rm FIXUP.INP
mv FIXUP.ENDF $work/$file-f2.endf
mv FIXUP.LST $work/$file-log.fixup2


# RUN LINEAR

ln -sf $file-f2.endf ENDF.IN
ln -sf $EMPIREDIR/util/linear/LINEAR.INP LINEAR.INP

$EMPIREDIR/util/linear/linear < LINEAR.INP
rm ENDF.IN
rm LINEAR.INP
mv LINEAR.OUT $work/$file-lin.endf
mv LINEAR.LST $work/$file-log.linear

# RUN RECENT

ln -sf $work/$file-lin.endf ENDF.IN
ln -sf $EMPIREDIR/util/recent/RECENT.INP RECENT.INP

$EMPIREDIR/util/recent/recent < RECENT.INP
rm ENDF.IN
rm RECENT.INP
mv RECENT.OUT $work/$file-rec.endf
mv RECENT.LST $work/$file-log.recent

# RUN SIGMA1

ln -sf $work/$file-rec.endf ENDF.IN
ln -sf $EMPIREDIR/util/sigma1/SIGMA1.INP SIGMA1.INP

$EMPIREDIR/util/sigma1/sigma1 < SIGMA1.INP
rm ENDF.IN
rm SIGMA1.INP
mv SIGMA1.OUT $work/$file-sig.endf
mv SIGMA1.LST $work/$file-log.sigma1

# RUN LEGEND

rm $file-l.endf 2>/dev/null
ln -sf $work/$file-sig.endf ENDF.IN
ln -sf $EMPIREDIR/util/legend/LEGEND.INP LEGEND.INP

$EMPIREDIR/util/legend/legend < LEGEND.INP
rm ENDF.IN
rm LEGEND.INP
mv LEGEND.OUT $work/$file-l.endf
mv LEGEND.LST $work/$file-log.legend

# RUN SIXTAB TO PREPARE FILE 6 FOR PLOTTING

rm $file-s.endf 2>/dev/null
ln -sf $work/$file-l.endf ENDF.IN
ln -sf $EMPIREDIR/util/sixtab/SIXTAB.INP SIXTAB.INP

$EMPIREDIR/util/sixtab/sixtab < SIXTAB.INP
rm ENDF.IN 
rm SIXTAB.INP SIXTAB.TMP
mv ENDF.OUT $work/$file-s.endf


# RUN PLTLST TO PRODUCE LISTING OR PLOTC4
 $EMPIREDIR/scripts/plotlst $file

# REMOVE INTERMEDIATE ENDF FILES

rm $work/$file-l.endf 2>/dev/null
rm $work/$file-lin.endf 2>/dev/null
rm $work/$file-f.endf 2>/dev/null
rm $work/$file-f2.endf 2>/dev/null
rm $work/$file-rec.endf 2>/dev/null
rm $work/$file-e.endf 2>/dev/null

exit
