#! /bin/sh -
#script to reconstruct inelastic, (n,p) and (n,alpha) reactions
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
work=`pwd`
if [ "$1" = "" ]
   then
echo 'Inputs ready to run'
echo ' '
ls *.endf
echo ' '
echo -n 'Choose one of the above (without .endf extention!): '
read file
fi


# RECONSTRUCT INELASTIC, (N,P) AND (N,A) REACTIONS WITH FIXUP

# The FIXUP input below is commented since a more restrictive input is being used
#cat >FIXUP.INP <<EOF
#12101011111001
#$file.endf
#$file-tmp.endf
#S  4=+( 50, 91)
#S103=+(600,649)
#S104=+(650,699)
#S105=+(700,749)
#S106=+(750,799)
#S107=+(800,849)
#
# 0.00000+00 0.00000+00          0          0${2}103
#
# 0.00000+00 0.00000+00          0          0${2}107
#
#
#
#EOF

# RECONSTRUCT INELASTIC, AND (N,P) REACTIONS WITH FIXUP
cat >FIXUP.INP <<EOF
12101011111001
$file.endf
$file-tmp.endf
S  4=+( 50, 91)
S103=+(600,649)

 0.00000+00 0.00000+00          0          0${2}103



EOF

$EMPIREDIR/util/fixup/fixup < FIXUP.INP

mv FIXUP.LST $work/$file-log.fixup
if [ ! -f $file-tmp.endf ]; then
    echo "FIXUP output file ($file-tmp.endf) with reconstructed chrg. part. channels was not created."
    echo " Hit any button to exit "
    read a
    exit
fi
rm FIXUP.INP

# RUN STAN
rm $file-tmp.STN 2>/dev/null
echo "Running STAN"

$EMPIREDIR/scripts/stanef $file-tmp

if [ ! -f $file-tmp.STN ]; then
    echo " STAN output file ($file-tmp.STN) with reconstructed chrg. part. channels was not created."
    echo " Hit any button to exit "
    read a
    exit
fi

#echo " Do you want to replace current $file.endf with the STAN result (Y/n)?"
#read a
#if [ $a = "y" ]; then 
#   mv $file-full.endf $file.endf    
#fi

exit
