#! /bin/sh -
#script to reconstruct total cross section as a sum of partials
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
MATid=$2
work=`pwd`
if [ "$2" = "" ]; then
  MATid='1111'
fi

if [ "$1" = "" ]
   then
echo 'Inputs ready to run'
echo ' '
ls *.endf
echo ' '
echo -n 'Choose one of the above (without .endf extention!): '
read file
fi


# RECONSTRUCT REDUNDANT REACTIONS WITH FIXUP (Out: FIXUP1.ENDF)
rm -f FIXUP1.ENDF 2>/dev/null
cat >FIXUP.INP <<EOF
10002011111001                                                              
$file.endf
FIXUP1.ENDF
 2.60540+ 3 0.00000+00          0          0${2}  3
 0.00000+ 0 0.00000+ 0          0          0           
 2.60540+ 3 0.00000+00          0          0${2}  4
 0.00000+ 0 0.00000+ 0          0          0           
 2.60540+ 3 0.00000+00          0          0${2}103
 0.00000+ 0 0.00000+ 0          0          0           



EOF
$EMPIREDIR/util/prepro/fixup < FIXUP.INP
mv FIXUP.LST $work/$file-log1.fixup
if [ ! -f FIXUP1.ENDF ]; then
    echo " FATAL ERROR:"
    echo " FIXUP output file (FIXUP1.ENDF) with reconstructed  redundant x-sec was not created."
    echo " Hit any button to exit "
    read a
    exit
fi



echo " Moving FIXUP result back to  " $file.endf
mv FIXUP1.ENDF $file.endf

# RUN STAN
echo "Running STAN"
$EMPIREDIR/scripts/stanef $file 

rm FIXUP.INP FIXUP1.ENDF 2>/dev/null

exit

