#! /bin/sh -
#script to reconstruct elastic as total-all_the_rest
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
MATid=$2
work=`pwd`
if [ "$2" = "" ]; then
  MATid='1111'
fi

if [ "$1" = "" ]
   then
echo 'Inputs ready to run'
echo ' '
ls *.endf
echo ' '
echo -n 'Choose one of the above (without .endf extention!): '
read file
fi

# RECONSTRUCT (N,ELA) WITH FIXUP

rm -f $file-tmp.endf 2>/dev/null
cat >FIXUP.INP <<EOF
10101011111001                                                              
$file.endf
$file-tmp.endf
S  4=+( 50, 91)
S103=+(600,649)
S104=+(650,699)
S105=+(700,749)
S106=+(750,799)
S107=+(800,849)
S  3=+(  4,  5)+( 11, 18)+( 22, 26)+( 28, 37)+( 41, 45)+( 102, 117)
S  1=+(  3,  3)+(  2,  2)

 0.00000+ 0 0.00000+00          0          0${2}  2
                                                   

                                                   







                                                                      
                                                                      
EOF

$EMPIREDIR/util/fixup/fixup < FIXUP.INP

mv FIXUP.LST $work/$file-log.fixup
if [ ! -f $file-tmp.endf ]; then
    echo " FATAL ERROR:"
    echo " FIXUP output file ($file-tmp.endf) with reconstructed  total x-sec was not created."
    echo " Hit any button to exit "
    read a
    exit
fi
echo " Moving FIXUP result back to  " $file.endf
mv $file-tmp.endf $file.endf


# RUN STAN
echo "Running STAN"
$EMPIREDIR/scripts/stanef $file 

exit

