#! /bin/sh -
#script to reconstruct elastic as total-all_the_rest
file=$1
work=`pwd`
if [ "$1" = "" ]
   then
echo 'Inputs ready to run'
echo ' '
ls *.endf
echo ' '
echo -n 'Choose one of the above (without .endf extention!): '
read file
fi

# RECONSTRUCT (N,ELA) WITH FIXUP

rm $file-rela.endf 2>/dev/null
cd ../util/fixup/
rm OUTPUT.ENDF 2>/dev/null
ln -sf $work/$file.endf OUTPUT.ENDF
rm -f FIXUP.INP
cat >FIXUP.INP <<EOF
10101111111001                                                              
OUTPUT.ENDF                                                                        
FIXUP.ENDF  
S104=+(650,699)
S105=+(700,749)
S106=+(750,799)
S  3=+(  4,  5)+( 11, 18)+( 22, 26)+( 28, 37)+( 41, 45)+( 102, 117)
S  2=+(  1,  1)-(  3,  3)

 0.00000+ 0 0.00000+00          0          01111  2
                                                   

                                                   







                                                                      
                                                                      
EOF
./fixup
rm OUTPUT.ENDF
mv FIXUP.ENDF $work/$file-rela.endf
mv FIXUP.LST $work/$file-log.fixup
cd $work

# RUN STANEF

rm -f INPUT
cat >INPUT <<EOF
$file-rela.endf
$file-stan.endf
0

DONE
EOF
../util/stanef/stanef <INPUT
mv $file-stan.endf $file.endf
rm -f INPUT 2>/dev/null 
rm $file-rela.endf

exit

