#! /bin/sh -
#script to reconstruct total cross section as a sum of partials
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
MATid=$2
work=`pwd`
if [ "$2" = "" ]; then
  MATid='1111'
fi

if [ "$1" = "" ]
   then
echo 'Inputs ready to run'
echo ' '
ls *.endf
echo ' '
echo -n 'Choose one of the above (without .endf extention!): '
read file
fi

# RECONSTRUCT REDUNDANT REACTIONS WITH FIXUP (Out: FIXUP1.ENDF)
rm -f FIXUP1.ENDF 2>/dev/null
cat >FIXUP.INP <<EOF
10002011111001                                                              
$file.endf
FIXUP1.ENDF
 2.60540+ 3 0.00000+00          0          0${2}  3
 0.00000+ 0 0.00000+ 0          0          0           
 2.60540+ 3 0.00000+00          0          0${2}  4
 0.00000+ 0 0.00000+ 0          0          0           
 2.60540+ 3 0.00000+00          0          0${2}103
 0.00000+ 0 0.00000+ 0          0          0           



EOF
$EMPIREDIR/util/prepro/fixup < FIXUP.INP
mv FIXUP.LST $work/$file-log1.fixup



# CHECK THAT THE testfile CONTAINS FEND RECORD AT THE END AND IS OF NON-TRIVIAL LENGTH (>5 LINES)
# IF SAFE OVERWRITE $file.endf
testfile=FIXUP1.ENDF
if [ ! -f $testfile ]; then
    echo " FATAL ERROR:"
    echo " Output file " $testfile " has not been created."
    echo " Hit any button to exit "
    read a
    exit
fi
fend=`tail -1 $testfile | cut -c 69-70`
nlines=`cat $testfile | wc -l`
echo ' '
echo $testfile ' ends with:' `tail -1 $testfile`
if [ $fend = -1 ]; then
   echo 'ENDF file has ' $nlines ' lines and ends with the FEND record' 
   if [ $nlines > 5 ]; then
      echo $testfile ' assumed correct and will overwrite' $file.endf
      mv $testfile $file.endf
   else
      echo 'Not enough lines in ' $testfile
      echo 'Processing has failed - EXIT without overwritting ' $file.end
      exit
   fi
else 
   echo 'Not a legal FEND record at the end of ' $testfile
   echo 'Processing has failed - EXIT without overwritting ' $file.endf
fi



# RUN STAN
echo "Running STAN"
$EMPIREDIR/scripts/stanef $file 

rm FIXUP.INP FIXUP1.ENDF 2>/dev/null

exit

