#!/usr/bin/env python
# encoding: utf-8
"""
run.py

modified version by Caleb Mattoon on 2008-12-19.

script to run full EMPIRE package
replaces bash version, this has error checking
"""

import sys
import os


def main():
	project = sys.argv[1]
	mat = sys.argv[2]
	# work = os.system('pwd')	# don't really need,
	# script will run in local dir unless specified otherwise
	
	# run EMPEND and FIXUP:
	
	os.system(" ../scripts/runE %s" % project )
	
	f = file( project+'.lst','r').readlines()
	try:
		f[-10:].index('  CALCULATIONS COMPLETED SUCCESSFULLY\n')
	except ValueError:
		print ("Empire did not finish successfully! Check the log.")
		print ("Press return to exit")
		raw_input()
		return 1
	
	# EMPEND, fixup, stanef:
	
	i,o,e = os.popen3( '../scripts/format %s %s' %(project, mat) )
	if not 'STANEF - Completed successfully' in e.readlines()[-1]:
		print ("STANEF did *not* finish successfully.")
		print ("Press return to exit")
		raw_input()
		return 1
	
	# run ENDF-6 checking codes
	
	i,o,e = os.popen3('../scripts/verify %s %s' %(project, mat) )
	for message in e.readlines():
		if not 'completed successfully' in message:
			print ("Failed a checking code. Final message:\n%s" % message)
			# assume these aren't fatal errors, we'll go on
	
	# run preprocessing codes in preparation for plotting
	
	i,o,e = os.popen3('../scripts/process %s %s' %(project, mat) )
	if not 'PLTLST Completed' in e.readlines()[-1]:
		print ("Trouble preprocessing files for plotting. Is c4 file present?")
		print ("Press return to exit")
		raw_input()
		return 1
	
	# plotc4 is run if the last parameter below is set to 2:
	# RUN PLOTC4 (disabled, hit 'Plot' on GUI (or run plot) to get PLOTC4 plots)
	
	
	# this next bit was to remove 'intermediate' ENDF files, but they appear to be
	# already removed (maybe by format or verify scripts):
	"""
	# REMOVE INTERMEDIATE ENDF FILES
	
	rm $work/$file-l.endf   2>/dev/null
	rm $work/$file-lin.endf 2>/dev/null
	rm $work/$file-f.endf   2>/dev/null
	rm $work/$file-rec.endf 2>/dev/null
	rm $work/$file-e.endf   2>/dev/null
	#rm $work/$file-s.endf   2>/dev/null
	"""
	
	# likewise, I don't see any of these 'empty files' on my system, so no reason
	# to remove them:
	"""
	# REMOVE EMPTY FILES
	
	if [ ! -s $file-omp.dir ]; then 
	       rm $file-omp.dir  2>/dev/null
	fi
	if [ ! -s $file-lev.col ]; then 
	       rm $file-lev.col  2>/dev/null
	fi
	if [ ! -s $file.war ]; then 
	       rm $file.war  2>/dev/null
	fi
	if [ ! -s $file-ecis.in ]; then 
	       rm $file-ecis.in  2>/dev/null
	fi
	if [ ! -s $file-ecis.out ]; then 
	       rm $file-ecis.out  2>/dev/null
	fi
	if [ ! -s $file-inp.fis ]; then 
	       rm $file-inp.fis  2>/dev/null
	fi
	
	"""
	return 0


if __name__ == '__main__':
	main()

