#! /bin/sh
# script to run three inputs in different energy ranges
# and to create single output file
# Note: energies should be in increasing order
# Output file will then be formatted
#
root=$1
echo 'running ' $root
ln -s $root.c4 $root-a.c4 
ln -s $root.exf $root-a.exf 
ln -s $root.lev $root-a.lev 
ln -s $root-lev.col $root-a-lev.col 
if [ -f $root-a-inp.fis ] cp $root-inp.fis $root-a-inp.fis 
if [ -f $root-a-omp.ripl ] cp $root-omp.ripl $root-a-omp.ripl 
if [ -f $root-a-omp.dir ] cp $root-omp.dir $root-a-omp.dir 
../scripts/runE $root-a
ln -s $root.c4 $root-b.c4 
ln -s $root.exf $root-b.exf 
ln -s $root.lev $root-b.lev 
ln -s $root-lev.col $root-b-lev.col 
if [ -f $root-b-inp.fis ] cp $root-inp.fis $root-b-inp.fis 
if [ -f $root-b-omp.ripl ] cp $root-omp.ripl $root-b-omp.ripl 
if [ -f $root-b-omp.dir ] cp $root-omp.dir $root-b-omp.dir 
../scripts/runE $root-b
ln -s $root.c4 $root-c.c4 
ln -s $root.exf $root-c.exf 
ln -s $root.lev $root-c.lev 
ln -s $root-lev.col $root-c-lev.col 
if [ -f $root-c-inp.fis ] cp $root-inp.fis $root-c-inp.fis 
if [ -f $root-c-omp.ripl ] cp $root-omp.ripl $root-c-omp.ripl 
if [ -f $root-c-omp.dir ] cp $root-omp.dir $root-c-omp.dir 
../scripts/runE $root-c
cat $root-a.out $root-b.out $root-c.out >$root.out
cat $root-a.lst $root-b.lst $root-c.lst >$root.lst
# RUN EMPEND, & ENDRES (ENDF FORMATING) 
../scripts/format $file  

# RUN ENDF-6 CHECKING CODES

../scripts/verify $file

# RUN PREPROCESSING CODES IN PREPRATION FOR PLOTTING 
# PLOTC4 IS RUN IF THE LAST PRAMETER BELOW IS SET TO 2

../scripts/process $file $2
 
# RUN PLOTC4 (disabled, hit 'Plot' on GUI (or run plot) to get PLOTC4 plots)

#../scripts/plot $file 1

# REMOVE INTERMEDIATE ENDF FILES

exit
