#! /bin/sh
# script to run three inputs in different energy ranges
# and to create single output file
# Note: energies should be in increasing order
# Output file will then be formatted
#
root=$1
echo 'running ' $root
../scripts/runE $root-a
cp $root-a.c4 $root-b.c4 
cp $root-a.exf $root-b.exf 
cp $root-a.lev $root-b.lev 
cp $root-a-lev.col $root-b-lev.col 
cp $root-a-omp.int $root-b-omp.int 
cp $root-a-omp.ripl $root-b-omp.ripl 
../scripts/runE $root-b
cp $root-a.c4 $root-c.c4 
cp $root-a.exf $root-c.exf 
cp $root-a.lev $root-c.lev 
cp $root-a-lev.col $root-c-lev.col 
cp $root-a-omp.int $root-c-omp.int 
cp $root-a-omp.ripl $root-c-omp.ripl 
../scripts/runE $root-c
cat $root-a.out $root-b.out $root-c.out >$root.out
../scripts/format $root
cp $root-a.c4 $root.c4 
cp $root-a.exf $root.exf 
rm $root-b.c4 $root-c.c4 2>/dev/null
rm $root-b.exf $root-c.exf 2>/dev/null
rm $root-b.lev $root-c.lev 2>/dev/null
rm $root-b-lev.col $root-c-lev.col 2>/dev/null
rm $root-b-omp.int $root-c-omp.int 2>/dev/null
rm $root-b-omp.ripl $root-c-omp.ripl 2>/dev/null
exit
