#! /bin/sh -
# Script to run Empire for all the input files in benchmarks directory, 
# keeping only the original files and the .lst and .xsc files
#
option=$1

cd $EMPIREDIR/benchmarks

files="a-ni58-pcross       
       d-au197             
       fe54-blind          
       fe54-vib-CC-direct-2
       HI-pcross-ccfus     
       n_eu153-dir-msc-msd 
       ni62-th-EGSM        
       n-na23-prim-gam     
       n-zr92-soft--dccomp 
       p-th232             
       p-tl205             
       test-HRTW-fis       
       test-LD-mo100       
       test-PE-models      
       th232-rot-vib       
       u235-blind          
       u235-pfns-nubar     
       u238-blind          
       u238-gf             
       u238-HFB-num-fis    
       u238-HFB-num-fis-tun
       u238-HFB-par-fis    
       u238-rigid-soft-omp 
       u238-rot-CC-direct-2"


suffix_list="xsc lst out"


if [ "$option" = "run" ] ; then
   echo "Running benchmarks..."

   mkdir TeMpOrArYdIr
#  cp * > TeMpOrArYdIr
   cp th232-rot-vib-lev.col u238-HFB-num-fis-tun-inp.fis TeMpOrArYdIr/
   for file in $files
   do
     $EMPIREDIR/scripts/runE $file
     cp $file.inp $file-ref.* TeMpOrArYdIr/
     for suffix in $suffix_list
     do
       cp $file.suffix TeMpOrArYdIr/
     done
   done

   rm * >& /dev/null
   rm -r *-tl  >& /dev/null
   mv TeMpOrArYdIr/* ./
   rm -r TeMpOrArYdIr >& /dev/null

elif [ "$option" = "clean" ] ; then
# cleans the benchmarks directory, keeping only original files
   mkdir TeMpOrArYdIr
   mv *-ref.* TeMpOrArYdIr/
   mv th232-rot-vib-lev.col TeMpOrArYdIr/
   mv u238-HFB-num-fis-tun-inp.fis TeMpOrArYdIr/
   cp *.inp TeMpOrArYdIr/ 
   for file in $files
   do
     $EMPIREDIR/scripts/clean $file
   done
   rm * >& /dev/null
   mv TeMpOrArYdIr/* ./
   rm -r TeMpOrArYdIr >& /dev/null


elif [ "$option" = "diff" ] ; then
# use diff -y  command to compare files .xsc, lst, and .out from benchmark runs and existing reference files
#
   for file in $files
   do
     for suffix in $suffix_list
     do
       string=$( wc -L $file.$suffix  )
       read length1 rubbish <<< "$string"
       string=$( wc -L $file-ref.$suffix  )
       read length2 rubbish <<< "$string"
       if [ $length1 -gt $length2 ]; then
         length=$(( ($length1 + 10)*2 ))
       else
         length=$(( ($length2 + 10)*2 ))
       fi
       diff --expand-tabs --side-by-side --width=$length $file.$suffix $file-ref.$suffix > diff.$file.$suffix
     done
   done
   
elif [ "$option" = "kompare" ] ; then
# use kompare to compare files .lst and .xsc from benchmark runs and existing reference files
#
   echo "Running kompare..."
   for file in $files
   do
     for suffix in $suffix_list
     do
       kompare $file.$suffix $file-ref.$suffix            
     done
   done

elif [ "$option" = "replace" ] ; then
#  renames the files .xsc and .lst to -ref.xsc and -ref.lst to serve as reference
#  using perl-based new version of linux 'rename' command
   echo 'Renaming cross-section and .lst files for reference'
   for suffix in $suffix_list
   do   
     rm *-ref.$suffix  >& /dev/null
     rename 's/\.$suffix$/\-ref\.$suffix/'  *.$suffix
   done

else
   echo
   echo "Current options are:"
   echo
   echo " 'run' to run benchmarks"
   echo " 'clean' to remove temporary files and keep only original ones"
   echo " 'diff' to compare benchmarks output with existing reference files (using diff command)"
   echo " 'kompare' to compare benchmarks output with existing reference files (using kompare)"
   echo " 'replace' to replace existing reference files with benchmarks outputs (using perl-based 'rename' command)"
   echo
fi   
