#! /bin/sh -
# Script to run Empire for all the input files in benchmarks directory, 
# keeping only the original files and the .lst and .xsc files
#
cd $EMPIREDIR/benchmarks
$EMPIREDIR/scripts/runE a-ni58-pcross          
$EMPIREDIR/scripts/runE d-au197                    
$EMPIREDIR/scripts/runE fe54-blind                 
$EMPIREDIR/scripts/runE fe54-vib-CC-direct-2   
$EMPIREDIR/scripts/runE HI-pcross-ccfus         
$EMPIREDIR/scripts/runE n_eu153-dir-msc-msd        
$EMPIREDIR/scripts/runE ni62-th-EGSM         
$EMPIREDIR/scripts/runE n-na23-prim-gam        
$EMPIREDIR/scripts/runE n-zr92-soft--dccomp         
$EMPIREDIR/scripts/runE p-th232                           
$EMPIREDIR/scripts/runE p-tl205                 
$EMPIREDIR/scripts/runE test-HRTW-fis               
$EMPIREDIR/scripts/runE test-LD-mo100            
$EMPIREDIR/scripts/runE test-PE-models                
$EMPIREDIR/scripts/runE th232-rot-vib                 
$EMPIREDIR/scripts/runE u235-blind                 
$EMPIREDIR/scripts/runE u235-pfns-nubar              
$EMPIREDIR/scripts/runE u238-blind                 
$EMPIREDIR/scripts/runE u238-gf                   
$EMPIREDIR/scripts/runE u238-HFB-num-fis          
$EMPIREDIR/scripts/runE u238-HFB-num-fis-tun         
$EMPIREDIR/scripts/runE u238-HFB-par-fis          
$EMPIREDIR/scripts/runE u238-rot-CC-direct-2           
mv th232-rot-vib-lev.col temporaryfile
mv u238-HFB-num-fis-tun-inp.fis temporaryfile2
rm -r *-tl *.out *.lev *.ripl *.rng *.war *.zvd file* *.c4 *fiss.xsc *.sys *.col *omp.dir *optman* spec *omp.ripl *ecis* *-inp.fis *-hms.lst >& /dev/null
mv temporaryfile th232-rot-vib-lev.col
mv temporaryfile2 u238-HFB-num-fis-tun-inp.fis
