#! /bin/sh -
# Script to run Empire for all the input files in test-cases directory, 
# keeping only the original files and the .lst, .xsc, .out, .endf, and -s.endf files
#
cd $EMPIREDIR/test-cases
$EMPIREDIR/scripts/runE a-ni58-pcross  
$EMPIREDIR/scripts/runE HI-pcross-ccfus
$EMPIREDIR/scripts/multiE pd105 1111 1 1 1 1 0
$EMPIREDIR/scripts/multiE pu240 1112 1 1 1 1 0
$EMPIREDIR/scripts/runE u238-photo-fiss
rm -r *-tl  *.lev *.ripl *.rng *.war *.zvd file* *.c4 *fiss.xsc *.sys *.col *omp.dir *optman* spec *omp.ripl *ecis* *-inp.fis *-log.* *fiss.out angdis.p92 *-e.endf *-endres.endf EMPIRE.OK>& /dev/null
#  renames the files .xsc and .lst to -ref.xsc and -ref.lst to serve as reference
#  using linux 'mv' command
echo 'Renaming cross-section and .lst files for reference'
suffix_list="xsc lst out endf"
files="a-ni58-pcross       
       HI-pcross-ccfus
       pd105          
       pu240
       u238-photo-fiss"
for file in $files
do
  for suffix in $suffix_list
  do   
    mv $file.$suffix $file-ref.$suffix
  done
done


