#!/bin/bash
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

export DISPLAY=:0
ln -s $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit        
for file in $*
do
$EMPIREDIR/util/c4zvd/zvview.exe -p:$file $file ps01.tit/c
if [ -f zv00.ps ]; then
   mv zv00.ps $file.ps
fi
if [ -f zv00.eps ]; then
   mv zv00.eps $file.eps
fi
done
rename 'zvd.ps' ps $file*
rename 'zvd.eps' eps $file*
rm ps01.tit
exit
