#!/bin/bash
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

XWIN=`uname`
if [ "$XWIN" = "Darwin" ] 
then
   if [ -z $DISPLAY ]; then export DISPLAY=:0 ; fi
fi

ln -s $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit        
for file in $*
do
$EMPIREDIR/util/c4zvd/zvview.exe -p:$file $file ps01.tit/c
    errCode=$?
    #echo -n "___Pause. Press any key..."; read yes
    #if [ $errCode -ne 0 ]; then
    if [ $errCode -ne 0 -a $errCode -ne 1 ]; then
        set +x
        echo    "___ERROR running ZVView: errCode=$errCode"
        echo    "___DISPLAY=$DISPLAY"
        echo -n "___Pause. Press any key..."; read yes
    fi
if [ -f zv00.ps ]; then
   mv zv00.ps $file.ps
fi
if [ -f zv00.eps ]; then
   mv zv00.eps $file.eps
fi
if [ -f zv.eps ]; then
   mv zv.eps $file.eps
fi
if [ -f zv00.zvd ]; then
   mv zv00.zvd $file.zvd	
fi
if [ -f ps01.zvd ]; then
   mv ps01.zvd $file.zvd
fi
done
rename 'zvd.ps' ps $file*
rename 'zvd.eps' eps $file*
rm ps01.tit
exit
