#! /bin/sh -
#SCRIPT TO SORT C4 FILE 
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
work=`pwd`
if [ "$1" = "" ]
   then
    echo 'Inputs ready to run'
    echo ' '
    ls *c4
    echo ' '
    echo -n 'Choose one of the above (without .c4 extention!): '
    read file
fi
echo ' '
if [ -f $file-raw.c4 ]; then
   echo 'Original C4 file stored as :'  $file-raw.c4
else
   echo 'Backup of the original C4 file:'  $file-raw.c4
   cp $file.c4 $file-raw.c4
fi
echo ' '
ln  -sf $file.c4 C4.DAT
# SORT C4 FILE
ln -sf $EMPIREDIR/util/c4sort/iaea-std.dat iaea-std.dat
cat >C4SORT.INP<<EOF
\$* C4SORT
          Sort the EXFOR file in C4 format NOT overwriting the original file
   FLC4IN C4.DAT
   FLC4OU C4.SRT
   FLESTD iaea-std.dat
   DPATH  $EMPIREDIR/RIPL/levels/

   ALIAS       92000    3    1     92238    3    1
   ALIAS       92000    3    2     92238    3    2
   ALIAS       92000    4    2     92238    4    2
   ALIAS       92000    4 9000     92238    4 9000
   ALIAS       92000    5 9000     92238    5 9000
   ALIAS       92000    6 9000     92238    6 9000

   ALIAS       14000    3    1     14028    3    1
   ALIAS       14000    5 9000     14028    5 9000
   ALIAS       14000    6 9000     14028    6 9000

   ALIAS       26000    3    1     26056    3    1
   ALIAS       26000    4    2     26056    4    2
   ALIAS       26000    5 9000     26056    5 9000
   ALIAS       26000    6 9000     26056    6 9000

   ALIAS       32000    3    1     32070    3    1
   ALIAS       32000    4    2     32070    4    2
   ALIAS       32000    5 9000     32070    5 9000
   ALIAS       32000    6 9000     32070    6 9000

   ENDC4S

\$* END
EOF

# RUN c4sort TO SORT C4 DATA   
$EMPIREDIR/util/c4sort/c4sort < C4SORT.INP

# ADD MU-BAR DATA TO THE C4 FILE
cat >ANG_MU.INP<<EOF
C4.SRT
C4.TMP
EOF

# RUN ang_mu
$EMPIREDIR/util/ang_mu/ang_mu < ANG_MU.INP
echo ' '
mv C4.TMP C4.DAT

# RUN c4sort the second time TO SORT C4 DATA   
$EMPIREDIR/util/c4sort/c4sort < C4SORT.INP

mv C4.SRT $file.c4
echo ' '
if [ -s $file.c4 ]; then
  echo 'EXFOR sorted data in computational (c4) format are stored in : '$file.c4
else
  echo 'File with EXFOR data in computational (c4) format is EMPTY'
fi
echo ' '
rm ANG_MU.INP C4SORT.INP C4SORT.TMP C4.DAT iaea-std.dat c4sort.scr C4SORT.TM2
rm angdis.pnt angdis.p92 angdis.cur 
exit
