#! /bin/sh -
#SCRIPT TO SORT C4 FILE 
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
work=`pwd`
if [ "$1" = "" ]
   then
    echo 'Inputs ready to run'
    echo ' '
    ls *c4
    echo ' '
    echo -n 'Choose one of the above (without .c4 extention!): '
    read file
fi                          
if [ -f $file-raw.c4 ]; then
   echo 'Using existing C4 file:'  $file-raw.c4
   else
   echo 'Input file :' $file-raw.c4 ' does not exist'
   exit
fi

ln  -sf $file-raw.c4 C4.DAT

# ADD MU-BAR DATA TO THE C4 FILE
cat >MU_BAR.INP<<EOF
C4.DAT
C4.TMP
EOF

# RUN ang_mu
$EMPIREDIR/util/ang_mu/ang_mu < ANG_MU.INP
rm C4.DAT

# SORT C4 FILE

cat >C4SORT.INP<<EOF
\$* C4SORT
          Sort the EXFOR file in C4 format NOT overwriting the original file
   FLC4IN C4.TMP
   FLC4OU C4.SRT
   DPATH  $EMPIREDIR/RIPL/levels/

   ALIAS       14000    3    1     14028    3    1
   ALIAS       14000    5 9000     14028    5 9000
   ALIAS       14000    6 9000     14028    6 9000

   ALIAS       26000    3    1     26056    3    1
   ALIAS       26000    4    2     26056    4    2
   ALIAS       26000    5 9000     26056    5 9000
   ALIAS       26000    6 9000     26056    6 9000

   ALIAS       32000    3    1     32070    3    1
   ALIAS       32000    4    2     32070    4    2
   ALIAS       32000    5 9000     32070    5 9000
   ALIAS       32000    6 9000     32070    6 9000

   ENDC4S

\$* END
EOF

# RUN c4sort TO SORT C4 DATA   
$EMPIREDIR/util/c4sort/c4sort < C4SORT.INP
mv C4.SRT $file.c4
rm C4.TMP

if [ -s $file.c4 ]; then
  echo 'EXFOR data in computational format are stored in :'$file.c4
    else
    echo 'File with EXFOR data in computational format is EMPTY'
  fi

rm MU_BAR.INP
rm C4SORT.INP
rm C4SORT.TMP
exit
