#! /bin/sh -
#script to standardize ENDF formatted file with STAN
# if processing is successful, result is renamed back to $1.endf

if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1

if [ "$1" = "" ]; then
	echo 'ENDF files ready to run'
	echo ' '
	ls *endf
	echo ' '
	echo -n 'Choose one of the above (without .endf extention!): '
	read file
fi                          



# RUN STAN

dos2unix $file.endf
$EMPIREDIR/util/stan/stan -x=1 -f --verbose -cm -o $file.STN $file.endf > $file-log.stan

if [ ! -f $file.STN ]; then
    echo " STAN output file ($file.STN)  was not created."
    echo " Check the input endf file " $file.endf
    echo " Opening log file with less (hit q and enter to exit less)"
    less $file-log.stan
    echo " Hit any button to exit "
    read a
    exit
fi

echo "  Renaming $file.STN as $file.endf"  >> $file-log.stan
mv $file.STN $file.endf 2>>$file-log.stan

exit
