#! /bin/sh -
#script to move all results of the calculations to another directory
if [ -d $1 ]; then
   echo 'O.K. directory:'  $1 ' exists'
   else
   mkdir $1              
   echo 'Have created directory:'  $1
fi                          
file=$2

mv -f $file* $1/ 2>/dev/null

# copy back still needed files
cp -p -f $1/$file.inp . 2>/dev/null
cp -p -f $1/$file.lev . 2>/dev/null
cp -p -f $1/$file-omp.ripl . 2>/dev/null
cp -p -f $1/$file.exf . 2>/dev/null
cp -p -f $1/$file.c4 . 2>/dev/null
cp -p -f $1/$file-lev.col . 2>/dev/null
cp -p -f $1/$file-inp.fis . 2>/dev/null



echo 'All files have been moved'
#echo 'Copies of .inp, .lev, -omp.ripl, .exf, .c4, and -lev.col files have been retained'
echo 'All input, omp, and levels files have been copied'
exit
