#! /bin/bash
#SCRIPT TO RETRIEVE EXFOR DATA FROM THE LOCAL DATABASE USING MYSQL
#NOTE: MYSQL SERVER WILL BE STARTED AT PORT=7777
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

#change to the x4cd/linux dir
work=`pwd`

#define X4 variables
X4CD=$EMPIREDIR/x4cd

#start MySQL server
$X4CD/linux/mysql_start.sh 7777 0

if [ -f $X4CD/x4vars.sh ]; then source $X4CD/x4vars.sh; fi

#run retrieval
$X4JRE/java -cp $JDBC:$X4CD/x4retr/bin/x4retr2.jar: x4retr2 \
	 -x4typ:$X4TYP -x4url:$X4URL -x4dat:$X4DB -x4usr:$X4USR -x4psw:$X4PSW \
	 -out:$work/EXFOR.dat -c:target:$1 -c:quant:$2 -c:React:$3

#shutdown MySQL server
$X4CD/linux/mysql_stop.sh

#mv EXFOR.dat $work/

exit

