#! /bin/sh -
#SCRIPT TO COMBINE TWO OR MORE zvd PLOTS INTO A SINGLE ONE
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

#export DISPLAY=:0
set -x
echo $1 $2
rm zv0*.ps zv0*.eps 2>/dev/null
file=$2
ln -s $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit
command="$EMPIREDIR/util/c4zvd/zvview.exe  ps01.tit/c"
        if [ "$file" = "" ]
           then
            echo 'Plots available for merging:'
            echo ' '
            ls *\.zvd
            echo ' '
            echo -n 'List files to be merged separating them by a space (include .zvd extention): '
            read file
        fi
        command=$command" "$file
ln -s $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit
$command ps01.tit/c
rm ps01.tit
if [ -f zv00.ps ]; then
   mv zv00.ps $file.ps
fi
if [ -f zv00.eps ]; then
   mv zv00.eps $file.eps
fi
rename 'zvd.ps' ps $file*
rename 'zvd.eps' eps $file*
rm ps01.tit
exit
