#! /bin/sh -
#SCRIPT TO COMBINE TWO OR MORE zvd PLOTS INTO A SINGLE ONE
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

# XWIN=`uname`
# if [ "$XWIN" = "Darwin" ]; then
#    if [ -z $DISPLAY ]; then export DISPLAY=:0 ; fi
# fi

set -x
echo $1 $2
rm zv0*.ps zv0*.eps ps0*.zvd 2>/dev/null
file=$2
if [ "$file" = "" ]; then
    echo 'Plots available for merging:'
    echo ' '
    ls *\.zvd
    echo ' '
    echo -n 'List files to be merged separating them by a space (include .zvd extention): '
    read file
fi
if [ ! -f ps01.tit ]; then
   cp $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit
   #ln -s $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit
fi

$EMPIREDIR/util/c4zvd/zvview.exe ps01.tit/c $file
    errCode=$?
    #echo -n "___Pause. Press any key..."; read yes
    #if [ $errCode -ne 0 ]; then
    if [ $errCode -ne 0 -a $errCode -ne 1 ]; then
        set +x
        echo    "___ERROR running ZVView: errCode=$errCode"
        echo    "___DISPLAY=$DISPLAY"
        echo -n "___Pause. Press any key..."; read yes
    fi

# rm ps01.tit
if [ -f zv00.ps ]; then
   mv zv00.ps $1-mrg.ps
fi
if [ -f zv00.eps ]; then
   mv zv00.eps $1-mrg.eps
fi
if [ -f ps01.zvd ]; then
   mv ps01.zvd $1-mrg.zvd
fi
rename 'zvd.ps' ps $1-mrg*
rename 'zvd.eps' eps $1-mrg*
rename 'zvd.zvd' zvd $1-mrg*

if [ -f $1-mrg.ps ]; then
   ps2pdf -dEPSCrop $1-mrg.ps
fi
if [ -f $1-mrg.eps ]; then
   ps2pdf -dEPSCrop $1-mrg.eps
fi
exit
