#! /bin/sh -
#SCRIPT TO COMBINE TWO OR MORE zvd PLOTS INTO A SINGLE ONE
echo $1 $2
rm zv0*.ps zv0*.eps 2>/dev/null
file=$2
command="../util/c4zvd/zvview.exe -p:$file ps01.tit/c"
        if [ "$file" = "" ]
           then
            echo 'Plots available for merging:'
            echo ' '
            ls *\.zvd
            echo ' '
            echo -n 'List files to be merged separating them by a space (include .zvd extention): '
            read file
        fi
        command=$command" "$file
ln -s ../util/c4zvd/ps01.tit ps01.tit
$command ps01.tit/c
rm ps01.tit
if [ -f zv00.ps ]; then
   mv zv00.ps $file.ps
fi
if [ -f zv00.eps ]; then
   mv zv00.eps $file.eps
fi
rename 'zvd.ps' ps $file*
rename 'zvd.eps' eps $file*
rm ps01.tit
exit
