#! /bin/sh -
#script to  display exp. and calculated data with ZVView

XWIN=`uname`
if [ "$XWIN" = "Darwin" ] 
    then
    export DISPLAY=:0
fi
file=$1
MT=$2
work=`pwd`
if [ "$1" = "" ]
    then
    echo 'Inputs ready to run'
    echo ' '
    ls *endf  
    echo ' '
    echo -n 'Choose one of the above (without .endf extention!): '
    read file
fi                          
if [ "$2" = "" ]
    then
    echo -n 'Input MT number to be plotted: '
    read MT
fi                          

if [ ! -f $file-s.endf ]; then
    $EMPIREDIR/scripts/process $file 
fi

# RUN ZVD
c4zvd_dir=$EMPIREDIR/util/c4zvd
c4zvd33_dir=$EMPIREDIR/util/endf33zvd

ln -sf $work/$file-s.endf Present
#ln -sf $work/$file.c4 c4
cp $work/$file.c4 c4
head c4
#$c4zvd_dir/c4zvv $MT $file 
rm tmp.dat c4.zvd end.zvd $file-$MT.zvd  zv*.ps zv*.eps 2>/dev/null
$c4zvd_dir/c4dat4l.exe c4 tmp.dat MF=3 MT=$MT
echo 'top of tmp.dat'
head tmp.dat
$c4zvd_dir/datzvdl.exe tmp.dat c4.zvd
echo 'top of c4.zvd'
head c4.zvd
$c4zvd_dir/endzvdl.exe A $MT Present end.zvd
$c4zvd33_dir/endf33zvd_l.exe -mt:$MT -c:$file-$MT-cov.zvd -u:$file-$MT-unc.zvd Present
echo '#!zvview.exe' >$file-$MT.zvd
cat c4.zvd >$file-$MT.zvd
cat end.zvd >>$file-$MT.zvd
ln -sf $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit
$c4zvd_dir/zvview.exe -p:$file-$MT $file-$MT.zvd ps01.tit/c
rm ps01.tit 2>/dev/null

if [ -f zv00.ps ]; then
   mv zv00.ps $work/$file-$MT.ps
fi
if [ -f zv00.eps ]; then
   mv zv00.eps $work/$file-$MT.eps
fi
if [ -f zv.eps ]; then
   mv zv.eps $work/$file-$MT.eps
fi
if [ -f zv00.zvd ]; then
   mv zv00.zvd $work/$file-$MT.zvd
fi
rm c4.zvd end.zvd tmp.dat 2>/dev/null
=======
if [ -f ps01.zvd ]; then
   mv ps01.zvd $work/$file-$MT.zvd
fi
rm c4 Present c4.zvd end.zvd end*.zvd tmp.dat 2>/dev/null
exit
