#! /bin/sh -
#script to  display exp. and calculated data with ZVView by V. Zerkin
export DISPLAY=:0
file=$1
MT=$2
work=`pwd`
if [ "$1" = "" ]
   then
echo 'Inputs ready to run'
echo ' '
ls *endf  
echo ' '
echo -n 'Choose one of the above (without .endf extention!): '
read file
fi                          
if [ "$2" = "" ]
   then
echo -n 'Input MT number to be plotted: '
read MT
fi                          

# FIRST RECONSTRUCT (N,N), (N,P), AND (N,A) REACTIONS WITH FIXUP

if [ ! -f $file-s.endf ]; then
   cd ../util/fixup/
   rm OUTPUT.ENDF
   ln -sf $work/$file.endf OUTPUT.ENDF
   ./fixup
   rm OUTPUT.ENDF
   mv FIXUP.ENDF $work/$file-f.endf
   cd $work

   # RUN SIXTAB TO PREPARE FILE 6 FOR PLOTTING

   cd ../util/sixtab/
   rm ENDF.IN ENDF.OUT 2>/dev/null
   ln -sf $work/$file-f.endf ENDF.IN
   ./sixtab
   rm ENDF.IN
   mv ENDF.OUT $work/$file-s.endf
   cd $work
   if  [ -f $file-s.endf ]; then
      rm $file-f.endf 2>/dev/null
   fi   

fi


# RUN ZVD

cd ../util/c4zvd/
ln -sf $work/$file-s.endf Present
ln -sf $work/$file.c4 c4
#./c4zvv $MT $file 
rm tmp.dat c4.zvd end.zvd $file-$MT.zvd  zv*.ps zv*.eps 2>/dev/null
./c4dat4l.exe c4 tmp.dat MF=3 MT=$MT
./datzvdl.exe tmp.dat c4.zvd
./endzvdl.exe A $MT Present end.zvd
echo #!zvview.exe >$file-$MT.zvd
cat c4.zvd >$file-$MT.zvd
cat end.zvd >>$file-$MT.zvd
./zvview.exe -p:$file-$MT $file-$MT.zvd ps01.tit/c
mv $file-$MT.* $work
if [ -f zv00.ps ]; then
   mv zv00.ps $work/$file-$MT.ps
fi
if [ -f zv00.eps ]; then
   mv zv00.eps $work/$file-$MT.eps
fi
cd $work

exit
