#!/bin/bash
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

XWIN=`uname`
if [ "$XWIN" = "Darwin" ] 
then
   if [ -z $DISPLAY ]; then export DISPLAY=:0 ; fi
fi

set -x
blank=" "
list=""
for file in $*
do
list=$list$file$blank
done
if [ ! -f ps01.tit ]; then
   cp $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit
fi
$EMPIREDIR/util/c4zvd/zvview.exe -p:$file $list ps01.tit/c
    errCode=$?
    #echo -n "___Pause. Press any key..."; read yes
    #if [ $errCode -ne 0 ]; then
    if [ $errCode -ne 0 -a $errCode -ne 1 ]; then
        set +x
        echo    "___ERROR running ZVView: errCode=$errCode"
        echo    "___DISPLAY=$DISPLAY"
        echo -n "___Pause. Press any key..."; read yes
    fi
#rm ps01.tit
exit
