#!/bin/bash
export DISPLAY=:0
set -x
blank=" "
list=""
for file in $*
do
list=$list$file$blank
ln -s ../util/c4zvd/ps01.tit ps01.tit
done
../util/c4zvd/zvview.exe -p:$file $list ps01.tit/c
rm ps01.tit
exit
