#!/bin/bash
if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

export DISPLAY=:0
set -x
blank=" "
list=""
for file in $*
do
list=$list$file$blank
ln -s $EMPIREDIR/util/c4zvd/ps01.tit ps01.tit
done
$EMPIREDIR/util/c4zvd/zvview.exe -p:$file $list ps01.tit/c
rm ps01.tit
exit
