#! /bin/sh -
#SCRIPT TO PLOT ANG. DISTR. AND DOUBLE-DIFFERENTIAL CROSS SECTIONS

XWIN=`uname`
if [ "$XWIN" = "Darwin" ] 
then
export DISPLAY=:0
fi

if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
work=`pwd`
rm LSTTAB.CUR LSTTAB.PNT PLOTC4.LST EMPIRE.LST HF.DAT 2>/dev/null
ln -sf $work/$file.c4 C4.DAT
ln -sf $work/$file-s.endf ENDF.DAT
#next 2 links are for plotting inclusive spctra directly from EMPIRE
#output (*.lst). The second one must be adjusted!
#ln -sf $work/$file.lst EMPIRE.LST
#ln -sf $work/HFde-p/$file.lst HF.DAT
ln -sf $work/$file-log.plotc4 PLOTC4.LST

$EMPIREDIR/util/lsttab/lsttab <LSTTAB.INP
rm LSTTAB.INP 2>/dev/null

# stay in local dir, don't cd to util/c4zvd:
#make actual plot 
# Commented to avoiud getting message if zvview windows is closed by pressing X (RCN, Aug 2010)
#$EMPIREDIR/util/c4zvd/pntzvdl LSTTAB.PNT LSTTAB.CUR DDXPLOT.zvd \
#    || { echo; echo 'zvview plotting failed!'; read; }
$EMPIREDIR/util/c4zvd/pntzvdl LSTTAB.PNT LSTTAB.CUR DDXPLOT.zvd \
    || { echo; echo 'zvview closed'; }
mv DDXPLOT.zvd $work/$file-$2.zvd

# not needed now: files saved in local dir by default
#rm zv*.ps zv*.eps 2>/dev/null
#if [ -f zv00.ps ]; then
#   mv zv00.ps $work/$file-$2.ps
#fi
#if [ -f zv00.eps ]; then
#   mv zv00.eps $work/$file-$2.eps
#fi

#cd $work
rm C4.DAT ENDF.DAT LSTTAB.CUR LSTTAB.PNT PLOTC4.LST LSTTAB.LST cur.zvd pnt.zvd tmp.dat 2>/dev/null
exit

