#! /bin/sh -
file=$1
work=`pwd`
if [ "$1" = "" ]
   then
echo 'Data ready for plotting:'
echo ' '
ls *-s.endf
echo ' '
echo -n 'Choose one of the above (without -s.endf extention!): '
read file
fi                          

if [ ! -f $file-s.endf ]; then
   echo ' '
   echo ' '
   echo 'Error in plot; can not find: '$file-s.endf 
#  read bye
   exit
fi    

# RUN PLOTC4 TO PRODUCE PLOTS

cd ../util/plotc4
ln -sf $work/$file.c4 C4.DAT  
ln -sf $work/$file-s.endf ENDF.DAT 
echo ' '
echo 'R U N N I G    P L O T C 4'
./plotc4
rm C4.DAT ENDF.DAT 
mv plot.ps $work/$file.ps
mv PLOTC4.LST $work/$file-log.plotc4
cd $work
if [ "$2" = "" ]; then        
   ghostview -landscape $file.ps  
fi
exit
