#! /bin/sh -
#script to run EXFOR grep
rm X4SEL.RES 2>/dev/null
grep  $1  ../EXFOR/REAC_SIG.TXT >temp
if [ "$2" != "" ]
	   then
	grep  $2 temp >tmp
	mv tmp temp
fi                        
if [ "$3" != "" ]
	   then
	grep  $3 temp >tmp
	mv tmp temp
fi                        
if [ "$4" != "" ]
	   then
	grep  $4 temp >tmp
	mv tmp temp
fi                        
grep -v '\-M\|\-G' temp >tmp
mv tmp X4SEL.RES
#vi X4SEL.RES
