#! /bin/sh -
#SCRIPT TO COMBINE TWO OR MORE zvd PLOTS INTO A SINGLE ONE

rm zv0*.ps zv0*.eps 2>/dev/null
file=$1
command="../util/c4zvd/zvview.exe -p:$file" 
        if [ "$file" = "" ]
           then
            echo 'Plots available for merging:'
            echo ' '
            ls *\.zvd
            echo ' '
            echo -n 'List files to be merged separating them by a space (include .zvd extention): '
            read file
        fi            
        command=$command" "$file
$command
if [ -f zv00.ps ]; then
   mv zv00.ps $file-plot
   rename zvd-plot ps *
fi   
if [ -f zv00.eps ]; then
   mv zv00.eps $file-eplot
   rename zvd-eplot eps *
fi   
exit
