#! /bin/bash
echo '//'>$1.res
grep -f $1.pat $1.lst   |
awk '{if($1 ~ "Reaction") 
	{
	 for(i=1;i<=NF;i++) if($i =="MeV") v[NR]=$(i-1)
	}
        else
	{
	 for(i=1;i<=NF;i++) if($i =="mb") v[NR]=$(i-1)
	}
      }
     END {for(i=1;i<=NR/2;i++) print  v[2*i-1]*1e+6,"  ",v[i*2]/1000}' \
     >> $1.res

echo '//'>>$1.res
XWIN=`uname`
if [ "$XWIN" = "Darwin" ] 
then
  export DISPLAY=:0
fi
$EMPIREDIR/util/c4zvd/zvview.exe $1.res/u
