#! /bin/sh -
# SCRIPT TO RUN STANDARD NJOY TEST
# Usage: runjoy file_name [MAT_number]
#
MAT=$2
if [ "$2" = "" ]
   then
exec 3< $1.endf        #open file $1
read <&3               #read fir st line
read -n 66 <&3         #read 66 chracters from the second line
read -n 4 MAT <&3      #read MAT number
exec 3>&-              #close the file
echo 'Set MAT to '$MAT
fi
cp $1.endf tape20
cat>njoyinput <<EOF
 moder
 20 -21
 reconr
 -21 -22
 'EMPIRE test'/
 $MAT 1/
 .001/
 'EMPIRE test'/
 0/
 broadr
 -21 -22 -23
 $MAT 1/
 .001/
 293.6 400 600 800 1000 1200 1600 2000/
 0/
 unresr
 -21 -23 -24
 $MAT 1 7 1
 293.6 400 600 800 1000 1200 1600 2000/
 1e10 1e4 1e3 300 100 30 10/
 0/
 heatr
 -21 -24 -25 30/
 $MAT 6 0 1 0 2/
 302 303 304 402 443 444
 viewr
 30 70
 purr
 -21 -25 -26
 $MAT 1 7 20 32/
 293.6 400 600 800 1000 1200 1600 2000/
 1e10 1e4 1e3 300 100 30 10/
 0/
 gaspr
 -21 -26 -28
 moder
 -28 29
 viewr
 30 31/
 acer
 -21 -28 0 32 27
 1 0 1/
 'EMPIRE calculations'/
 $MAT 293.6 /
 /
 1e-5 2e+7 20/
 acer
 0 32 33 34 35
 7 1 1/
 'EMPIRE calculations'/
 viewr
 33 36/
 stop
EOF
xnjoy<njoyinput
mv output $1-njoy.out
#mv tape29 $1-29 
mv tape30 $1-njoy.chk 
mv tape31 $1-njoy.ps 

mv tape34 $1.ace
mv tape35 $1.xsdir
mv tape36 $1-acer.ps
mv tape70 $1-heater.ps
rm tape* njoyinput

