#! /bin/sh -
#script to standardize ENDF formatted file with STANEF
# if processing is successful, result is renamed back to $1.endf

if [ -z $EMPIREDIR ]; then
    echo "Please set the 'EMPIREDIR' environment variable."
    echo "See Empire v3 documentation for more information."
    exit
fi

file=$1
work=`pwd`
if [ "$1" = "" ]
   then
echo 'ENDF files ready to run'
echo ' '
ls *endf
echo ' '
echo -n 'Choose one of the above (without .endf extention!): '
read file
fi                          

# RUN STANEF

rm -f INPUT
cat >INPUT <<EOF
$file.endf
$file-stan.endf
0

DONE
EOF
$EMPIREDIR/util/stanef/stanef <INPUT 2>| err.log

if grep 'Completed successfully' err.log; then
    mv $file-stan.endf $file.endf
else
    echo STANEF did not finish successfully!
fi

rm err.log INPUT

exit
