      PARAMETER(
     * NDNUC= 55                   
     *,NDEJC=3 
     *,NDAFIS=1
     *,NDEX=100
     *,NDLW= 50
     *,NDTL= 30
     *,NDVOM=7
     *,NDWOM=7
     *,NDVSO=7
     *,NDRVOM=3
     *,NDRWOM=3
     *,NDRVSO=3
     *,NDLV=10
     *,NDHRTW1=500         
     *,NDHRTW2=10         
     *,NDETL=NDEX+5
     *,NDECSE=NDEX+10
     *,NDEREC=NDECSE
     *,NDERO=NDEX
     *,NDBR=11
     *,NDANG=19
     *,NDCC=10
     *,NDROPM=7
     *,NDGDRPM=10
     *,NDGQRPM=8
     *,NDGMRPM=8
     *,NDKNTR=3
     *,NDMSCS=3 
     *,NDREGIONS=5
     *,NDMODELS=5
     *,LMAX_CC=6
     *,MAX_Coll=20     
     *)
