      PARAMETER(
     * NDNUC= 60
     *,NDEXCLUS = 60
     *,NDEJC=3
     *,NDAFIS=1
     *,NDEX= 121
     *,NDLW= 35
     *,NDTL= 35
     *,NDMSCS=4
     *,NDLV=40
     *,NDBR=40
     *,NDECSE=NDEX+10
     *,NDANG=19
     *,NDNUCD=NDNUC
     *,NDECSED=NDECSE
     *,NDANGD=NDANG
     *,NDEX_D=NDEX
     *,NDEJCD=NDEJC
     *,NDVOM=7
     *,NDWOM=7
     *,NDVSO=7
     *,NDRVOM=3
     *,NDRWOM=3
     *,NDRVSO=3
     *,NDHRTW1=500
     *,NDHRTW2=10
     *,NDETL=NDEX+5
     *,NDEREC=NDECSE
     *,NDERO=NDEX
     *,NDCC=10
     *,NDROPM=7
     *,NDGDRPM=10
     *,NDGQRPM=8,NDGMRPM=8,NDKNTR=3,NMAsse=9066
     *,NDREGIONS=6,NDMODELS=6,NDDEFCC=6,NDCOLLEV=75
     *,NFtrans=50,NFMOD=3
     *,NFisEN=55,NFisJ=30,NFPARAB=5,NFHUMP=3,NFISENMAX=400)
