      SUBROUTINE THORA(IOUT)
C
C     GIVES THE TIME ELAPSED SINCE THE FIRST CALL AND SINCE THE LAST CALL
C              (LAHEY and MS FORTRAN compatible)
C
      REAL*8 DIFTIM,BEGTIM,ENDTIM,DIFTI1
      INTEGER*2 IHR,MIN,ISEC,I110,IH,MIN1,IS,I10
      INTEGER IOUT
      LOGICAL NEVER_CALLED
      DATA NEVER_CALLED/.TRUE./
      SAVE BEGTIM,NEVER_CALLED

      IF (NEVER_CALLED) then
        NEVER_CALLED = .FALSE.
        CALL GETTIM (IHR,MIN,ISEC,I110)
        BEGTIM=DBLE(IHR*3600.+MIN*60.+ISEC+I110*.01)
        WRITE(IOUT,1002) IHR,MIN,ISEC,I110
      ELSE
        CALL GETTIM (IH,MIN1,IS,I10)
        ENDTIM=DBLE(IH*3600.+MIN1*60.+IS+I10*.01)
        IF(ENDTIM.LT.BEGTIM) ENDTIM = ENDTIM +  86400.D0
        DIFTIM=(ENDTIM-BEGTIM)/60.
        DIFTI1=(DIFTIM-INT(DIFTIM))*60.
        WRITE(IOUT,1001) IH,MIN1,IS,I10,INT(DIFTIM),NINT(DIFTI1)
        WRITE(*,1001) IH,MIN1,IS,I10,INT(DIFTIM),NINT(DIFTI1)
      ENDIF

      RETURN
 1001 FORMAT (/15X,' CURRENT TIME: ',
     1 I2,3H H ,I2,5H MIN ,I2,5H SEC ,I2,5H HUN /
     1 15X,' CALCULATION TIME: ',I3,' MIN ',I2,' SEC'/)
 1002 FORMAT (/15X,' START TIME: ',
     1 I2,3H H ,I2,5H MIN ,I2,5H SEC ,I2,5H HUN /)
C====================================================================
      END

